//
//  AbdhaljsIslePurgonorgo.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct AbdhaljsIslePurgonorgo: ZoneSceneMetadata {
        public let id = Zone.abdhaljsIslePurgonorgo.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z0o0z0p1",
                position: .init(x: -482.59348, y: -20.100267, z: 283.52264),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 4.0, y: 10.0, z: 25.0)
            ),
            .init(
                name: "z0o1",
                position: .init(x: -475.8254, y: -20.461266, z: 281.14923),
                rotation: .init(x: 0.0, y: 0.21380283, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0o2z0q1",
                position: .init(x: -600.9893, y: -2.98115, z: -100.086006),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z0o3",
                position: .init(x: -596.49445, y: -2.9366748, z: -99.41965),
                rotation: .init(x: 0.0, y: 5.8643064, z: 0.0),
                scale: .init(x: 0.8, y: 3.0, z: 4.5)
            ),
            .init(
                name: "z0o4z0q3",
                position: .init(x: -401.48752, y: -3.0558143, z: -219.9579),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z0o5",
                position: .init(x: -398.02148, y: -2.5545473, z: -220.7798),
                rotation: .init(x: 0.0, y: 0.2443461, z: 0.0),
                scale: .init(x: 0.8, y: 3.0, z: 4.5)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}