//
//  AbysseaEmpyrealParadox.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct AbysseaEmpyrealParadox: ZoneSceneMetadata {
    public let id = Zone.abysseaEmpyrealParadox.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z2z0z6i1",
            position: .init(x: 580.03033, y: -3.2246504, z: -301.75992),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 10.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "z2z1",
            position: .init(x: 579.9932, y: -1.928333, z: -305.07715),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z2z2z6j5",
            position: .init(x: 260.0, y: -3.2246504, z: -180.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 10.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "z2z3",
            position: .init(x: 259.9629, y: -1.928333, z: -183.31723),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z2z4z2y3",
            position: .init(x: 0.877165, y: -6.76293, z: 80.1556),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 25.0, y: 15.0, z: 2.0)
        ),
        .init(
            name: "z2z5",
            position: .init(x: 0.840056, y: -5.026668, z: 76.8384),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 10.0)
        ),
        .init(
            name: "z2z6z2y5",
            position: .init(x: -440.46472, y: 33.268227, z: -118.43578),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 25.0, y: 15.0, z: 2.0)
        ),
        .init(
            name: "z2z7",
            position: .init(x: -440.50183, y: 35.485577, z: -121.753006),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 10.0)
        ),
        .init(
            name: "z2z8z5b1",
            position: .init(x: -605.34033, y: 33.825924, z: -520.2232),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 25.0, y: 15.0, z: 2.0)
        ),
        .init(
            name: "z2z9",
            position: .init(x: -601.4335, y: 35.20393, z: -520.03107),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 10.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}