//
//  AbysseaAttohwa.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct AbysseaAttohwa: ZoneSceneMetadata {
        public let id = Zone.abysseaAttohwa.rawValue
        public let name = "Abyssea - Attohwa"
        public let lines: [ZoneLine] = [
            .init(
                name: "z4p0z5cd",
                position: .init(x: -340.01117, y: 4.067849, z: 275.0486),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z4p1",
                position: .init(x: -339.99496, y: 5.940652, z: 278.01257),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z4p2z6n7",
                position: .init(x: 139.98383, y: -3.771301, z: 132.96231),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z4p3",
                position: .init(x: 139.99205, y: -2.1693146, z: 130.49197),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z4p4z4q1",
                position: .init(x: -260.00037, y: 21.102226, z: 85.82475),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z4p5",
                position: .init(x: -259.9797, y: 21.793888, z: 81.88719),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z4p6z4q3",
                position: .init(x: -323.99606, y: 8.864106, z: 260.00363),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z4p7",
                position: .init(x: -320.0029, y: 9.74226, z: 260.02228),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}