//
//  AbysseaAltepa.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct AbysseaAltepa: ZoneSceneMetadata {
    public let id = Zone.abysseaAltepa.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z4y0z3m1",
            position: .init(x: -40.000103, y: -4.4521527, z: -235.62111),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 8.0)
        ),
        .init(
            name: "z4y1",
            position: .init(x: -40.00541, y: -3.397785, z: -232.00018),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4y2z3m3",
            position: .init(x: -119.98776, y: -20.41415, z: -195.62955),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 8.0)
        ),
        .init(
            name: "z4y3",
            position: .init(x: -119.99307, y: -19.359781, z: -192.00862),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4y4z3m5",
            position: .init(x: 119.992516, y: -20.398289, z: -195.60974),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 8.0)
        ),
        .init(
            name: "z4y5",
            position: .init(x: 119.987206, y: -19.343922, z: -191.98882),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4y6z3md",
            position: .init(x: 355.70523, y: -4.4521527, z: -159.99335),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 8.0)
        ),
        .init(
            name: "z4y7",
            position: .init(x: 351.99628, y: -3.397785, z: -160.00186),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4y8z3mj",
            position: .init(x: 239.98528, y: -4.4521527, z: 355.6542),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 8.0)
        ),
        .init(
            name: "z4y9",
            position: .init(x: 239.99753, y: -3.397785, z: 352.00208),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4yaz3mp",
            position: .init(x: -240.01515, y: -4.4521527, z: 355.6553),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 8.0)
        ),
        .init(
            name: "z4yb",
            position: .init(x: -240.00288, y: -3.397785, z: 352.00317),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4ycz3mv",
            position: .init(x: -355.712, y: -4.4521527, z: -160.00038),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 8.0)
        ),
        .init(
            name: "z4yd",
            position: .init(x: -351.99542, y: -3.397785, z: -159.99109),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4yez511",
            position: .init(x: -0.023910077, y: 43.363094, z: 60.00802),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4yf",
            position: .init(x: -3.3802679, y: 46.326183, z: 59.99587),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}