//
//  AbysseaLaTheine.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct AbysseaLaTheine: ZoneSceneMetadata {
        public let id = Zone.abysseaLaTheine.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z0z1",
                position: .init(x: -420.0, y: -2.21622, z: 243.49098),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z0z0z0y7",
                position: .init(x: -420.0, y: -3.66898, z: 235.71236),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0z2z0z3",
                position: .init(x: -484.73944, y: -3.0, z: -340.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0z3",
                position: .init(x: -351.13635, y: -2.25, z: -380.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z0z4z0z5",
                position: .init(x: -355.1494, y: -3.0, z: -380.1405),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0z5",
                position: .init(x: -488.90833, y: -2.31766, z: -340.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z0z6z0z7",
                position: .init(x: -478.37393, y: -3.0, z: -339.9769),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0z7",
                position: .init(x: -365.29095, y: -2.25, z: -380.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z0z8z0z9",
                position: .init(x: -361.5975, y: -3.0, z: -380.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0z9",
                position: .init(x: -474.853, y: -2.25, z: -340.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z0zh",
                position: .init(x: -351.14334, y: -2.25, z: -340.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z0zez0zf",
                position: .init(x: -355.15692, y: -3.0, z: -340.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0zd",
                position: .init(x: -365.29794, y: -2.25, z: -340.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z0zaz0zb",
                position: .init(x: -361.6044, y: -3.0, z: -340.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0zgz0zh",
                position: .init(x: -484.7288, y: -3.0, z: -380.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0zf",
                position: .init(x: -488.89734, y: -2.25, z: -380.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z0zcz0zd",
                position: .init(x: -478.37546, y: -3.0, z: -380.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0zb",
                position: .init(x: -474.843, y: -2.25, z: -380.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z0ziz0zj",
                position: .init(x: -460.0, y: -2.5, z: -446.30527),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0zj",
                position: .init(x: -380.0, y: -2.25, z: -478.369),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
            .init(
                name: "z0zkz0zl",
                position: .init(x: -380.0, y: -3.5, z: -473.73282),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0zl",
                position: .init(x: -460.0, y: -2.25, z: -441.682),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
            .init(
                name: "z0zp",
                position: .init(x: -460.0, y: -2.25, z: -478.369),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
            .init(
                name: "z0zmz0zn",
                position: .init(x: -460.0, y: -3.5, z: -473.73282),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0zoz0zp",
                position: .init(x: -380.0, y: -3.5, z: -446.30527),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z0zn",
                position: .init(x: -380.0, y: -2.25, z: -441.682),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}