//
//  AbysseaMisareaux.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct AbysseaMisareaux: ZoneSceneMetadata {
        public let id = Zone.abysseaMisareaux.rawValue
        public let name = "Abyssea - Misareaux"
        public let lines: [ZoneLine] = [
            .init(
                name: "z4o0z5st",
                position: .init(x: -179.54741, y: -3.4310021, z: -42.006138),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z4o1",
                position: .init(x: -177.804, y: -2.7645264, z: -37.8932),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z4o2z5sv",
                position: .init(x: 184.91931, y: -1.79354, z: -100.04101),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 7.0, z: 12.0)
            ),
            .init(
                name: "z4o3",
                position: .init(x: 185.91444, y: -0.9097911, z: -96.41296),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}