//
//  AhtUrhganWhitegate.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct AhtUrhganWhitegate: ZoneSceneMetadata {
        public let id = Zone.ahtUrhganWhitegate.rawValue
        public let name = "Aht Urhgan Whitegate"
        public let lines: [ZoneLine] = [
            .init(
                name: "z1i0z277",
                position: .init(x: 499.99704, y: -20.7169, z: -43.50181),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 13.0, z: 13.0)
            ),
            .init(
                name: "z1i1",
                position: .init(x: 500.0188, y: -18.332996, z: -40.025707),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.5, y: 5.0, z: 4.5)
            ),
            .init(
                name: "z1i2z279",
                position: .init(x: 603.97833, y: -13.066115, z: 380.00003),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 13.0, z: 13.0)
            ),
            .init(
                name: "z1i3",
                position: .init(x: 600.0035, y: -10.332266, z: 379.99664),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.5, y: 5.0, z: 4.5)
            ),
            .init(
                name: "z1i4z27b",
                position: .init(x: -420.00012, y: -20.708761, z: -83.54311),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 13.0, z: 13.0)
            ),
            .init(
                name: "z1i5",
                position: .init(x: -420.00558, y: -18.33248, z: -79.99807),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.5, y: 5.0, z: 4.5)
            ),
            .init(
                name: "z1i6z27d",
                position: .init(x: -419.99472, y: -12.9176, z: -565.4943),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 13.0, z: 13.0)
            ),
            .init(
                name: "z1i7",
                position: .init(x: -419.99817, y: -10.333937, z: -561.26337),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.5, y: 5.0, z: -4.5)
            ),
            .init(
                name: "z1i8z27f",
                position: .init(x: -420.00815, y: -12.8539505, z: -276.43332),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 13.0, z: 13.0)
            ),
            .init(
                name: "z1i9",
                position: .init(x: -419.99796, y: -10.33214, z: -279.9962),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 5.0, z: 4.5)
            ),
            .init(
                name: "z1iaz27h",
                position: .init(x: -563.5169, y: -12.610355, z: 379.97034),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 13.0, z: 13.0)
            ),
            .init(
                name: "z1ib",
                position: .init(x: -559.9951, y: -10.332119, z: 380.00183),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 5.0, z: 4.5)
            ),
            .init(
                name: "z1icz1l3",
                position: .init(x: -180.00633, y: -12.713182, z: -563.5703),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 13.0, z: 13.0)
            ),
            .init(
                name: "z1id",
                position: .init(x: -180.02757, y: -10.334591, z: -559.9875),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.5, y: 5.0, z: 4.5)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}