//
//  AltarRoom.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct AltarRoom: ZoneSceneMetadata {
    public let id = Zone.altarRoom.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z2f0z2g1",
            position: .init(x: -233.95642, y: -4.231218, z: 105.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 20.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z2f1",
            position: .init(x: -233.87914, y: -2.000004, z: 94.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 5.0)
        ),
        .init(
            name: "zms2zms3",
            position: .init(x: -150.75, y: -6.766028, z: 29.920078),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 10.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "zms3",
            position: .init(x: -177.00021, y: -9.4, z: 30.025755),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 2.0, z: 6.0)
        ),
        .init(
            name: "zms4zms5",
            position: .init(x: -150.75, y: -6.78117, z: -30.32883),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 10.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "zms5",
            position: .init(x: -177.0, y: -9.4, z: -30.250608),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 2.0, z: 6.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}