//
//  AlTaieu.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct AlTaieu: ZoneSceneMetadata {
        public let id = Zone.alTaieu.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z7i0z7l7",
                position: .init(x: -219.784, y: 6.3273373, z: 524.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 14.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z7i1",
                position: .init(x: -219.869, y: 7.800387, z: 519.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z7i2z7h7",
                position: .init(x: 527.53107, y: 16.45536, z: 418.5591),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 14.0, y: 9.0, z: 2.0)
            ),
            .init(
                name: "z7i3",
                position: .init(x: 520.0, y: 17.918278, z: 419.832),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.5)
            ),
            .init(
                name: "z7i4z7k7",
                position: .init(x: -180.217, y: 26.995636, z: -321.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 14.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z7i5",
                position: .init(x: -179.4183, y: 27.688189, z: -315.1522),
                rotation: .init(x: 0.0, y: 4.9741883, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.5)
            ),
            .init(
                name: "z7i6z7g9",
                position: .init(x: 419.0, y: 36.782486, z: -286.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 14.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z7i7",
                position: .init(x: 420.0, y: 37.845177, z: -280.5),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z7i8z7b1",
                position: .init(x: 207.63199, y: 4.8927717, z: 217.93813),
                rotation: .init(x: 0.0, y: 1.9198622, z: 0.0),
                scale: .init(x: 14.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z7i9",
                position: .init(x: 200.5, y: 7.8948812, z: 220.03177),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}