//
//  AlzadaalUnderseaRuins.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct AlzadaalUnderseaRuins: ZoneSceneMetadata {
    public let id = Zone.alzadaalUnderseaRuins.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z791",
            position: .init(x: -300.5, y: -1.8596232, z: 400.0),
            rotation: .init(x: 0.0, y: 1.6580628, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.5)
        ),
        .init(
            name: "z790z781",
            position: .init(x: -299.713, y: -2.525062, z: 405.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 12.0, y: 8.0, z: 3.0)
        ),
        .init(
            name: "z792z783",
            position: .init(x: -20.3586, y: -3.0590088, z: 445.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 12.0, y: 8.0, z: 3.0)
        ),
        .init(
            name: "z794z785",
            position: .init(x: 340.376, y: -3.2359283, z: 364.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 12.0, y: 8.0, z: 3.0)
        ),
        .init(
            name: "z793",
            position: .init(x: -20.0, y: -1.8524885, z: 440.0),
            rotation: .init(x: 0.0, y: 1.6580628, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z795",
            position: .init(x: 340.708, y: -1.846093, z: 359.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z798z7g1",
            position: .init(x: -99.89082, y: 3.905744, z: -527.1754),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 13.0, y: 9.0, z: 3.0)
        ),
        .init(
            name: "z796z7g3",
            position: .init(x: -540.0, y: 4.9261985, z: -315.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 13.0, y: 8.0, z: 3.0)
        ),
        .init(
            name: "z799",
            position: .init(x: -100.0, y: 6.1557484, z: -521.9552),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z797",
            position: .init(x: -540.319, y: 6.19726, z: -320.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z79az743",
            position: .init(x: 460.78134, y: -1.3406626, z: 176.94089),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 13.0, y: 8.0, z: 3.0)
        ),
        .init(
            name: "z79b",
            position: .init(x: 431.0, y: -1.9275249, z: 178.0),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 8.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}