//
//  AlZahbi.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct AlZahbi: ZoneSceneMetadata {
        public let id = Zone.alZahbi.rawValue
        public let name = "Al Zahbi"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}