//
//  ArrapagoRemnants.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct ArrapagoRemnants: ZoneSceneMetadata {
        public let id = Zone.arrapagoRemnants.rawValue
        public let name = "Arrapago Remnants"
        public let lines: [ZoneLine] = [
            .init(
                name: "z0w0z0q9",
                position: .init(x: 599.803, y: 129.57, z: 802.149),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 12.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z0w1",
                position: .init(x: 600.101, y: 130.355, z: 797.612),
                rotation: .init(x: 0.0, y: 1.3089969, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}