//
//  ArrapagoRemnants.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct ArrapagoRemnants: ZoneSceneMetadata {
    public let id = Zone.arrapagoRemnants.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z070z5i5",
            position: .init(x: -167.10097, y: 5.011533, z: -261.7201),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z071",
            position: .init(x: -163.49588, y: 7.220984, z: -260.87186),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z072z081",
            position: .init(x: -191.03108, y: -16.407671, z: 336.81436),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z073",
            position: .init(x: -194.48695, y: -13.7660675, z: 338.70407),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z074z083",
            position: .init(x: -59.999046, y: -27.569841, z: 242.98586),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z075",
            position: .init(x: -60.008274, y: -25.908308, z: 239.49693),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}