//
//  BalgaSDais.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct BalgaSDais: ZoneSceneMetadata {
    public let id = Zone.balgaSDais.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z6m0z371",
            position: .init(x: -40.1942, y: -7.87097, z: 248.809),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 10.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z6m1",
            position: .init(x: -39.996117, y: -7.640336, z: 244.0347),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
        .init(
            name: "z6m2z6o3",
            position: .init(x: -59.5911, y: -7.1151237, z: -209.04454),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 10.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "z6m4z6n1",
            position: .init(x: 160.10829, y: -7.3033133, z: 60.360214),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 10.0, y: 12.0, z: 2.0)
        ),
        .init(
            name: "z6m3",
            position: .init(x: -59.5241, y: -5.3595886, z: -199.04593),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
        .init(
            name: "z6m5",
            position: .init(x: 153.45967, y: -4.9601727, z: 58.88265),
            rotation: .init(x: 0.0, y: 2.792527, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
        .init(
            name: "zmr6zmr7",
            position: .init(x: 159.93419, y: -8.386011, z: -64.08628),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 10.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "zmr7",
            position: .init(x: 159.97847, y: -7.71309, z: -61.890053),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}