//
//  BalgaSDais.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct BalgaSDais: ZoneSceneMetadata {
        public let id = Zone.balgaSDais.rawValue
        public let name = "Balga's Dais"
        public let lines: [ZoneLine] = [
            .init(
                name: "z6e0z2t3",
                position: .init(x: 113.458, y: -4.0788813, z: -57.3508),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 15.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z6e2z2s1",
                position: .init(x: -113.372, y: -4.07481, z: -57.4183),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 15.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z6e4z6f1",
                position: .init(x: 0.012850404, y: -8.469082, z: 57.96522),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 12.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z6e1",
                position: .init(x: 110.23378, y: -2.1268475, z: -54.222992),
                rotation: .init(x: 0.0, y: 3.9269907, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z6e3",
                position: .init(x: -110.465, y: -2.0827425, z: -54.4689),
                rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z6e5",
                position: .init(x: -0.00431602, y: -4.1823316, z: 54.388298),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 6.0)
            ),
            .init(
                name: "zmr0zmr1",
                position: .init(x: 164.93318, y: -5.5468006, z: 164.79182),
                rotation: .init(x: 0.0, y: 3.926991, z: 0.0),
                scale: .init(x: 12.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "zmr1",
                position: .init(x: 162.59119, y: -4.1026587, z: 162.42282),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}