//
//  BastokMarketsS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct BastokMarketsS: ZoneSceneMetadata {
    public let id = Zone.bastokMarketsS.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z7h0z7d1",
            position: .init(x: 99.5, y: 6.0, z: 116.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 14.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z7h1",
            position: .init(x: 100.0, y: 7.2971444, z: 121.0),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z7h2z789",
            position: .init(x: 300.0, y: 46.0, z: -364.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 14.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z7h3",
            position: .init(x: 300.0, y: 47.368874, z: -359.0),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z7h4z787",
            position: .init(x: 100.5, y: 46.0, z: -484.5),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 14.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z7h5",
            position: .init(x: 100.0, y: 47.3505, z: -479.5),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z7h6z7i3",
            position: .init(x: -126.26003, y: 38.8527, z: -381.55112),
            rotation: .init(x: 0.0, y: 1.2217305, z: 0.0),
            scale: .init(x: 14.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z7h7",
            position: .init(x: -120.923, y: 37.3481, z: -380.194),
            rotation: .init(x: 0.0, y: 6.0213857, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 3.5)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}