//
//  BatalliaDownsS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct BatalliaDownsS: ZoneSceneMetadata {
        public let id = Zone.batalliaDownsS.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z3e0z3d9",
                position: .init(x: -0.00096263736, y: -11.0351, z: -150.12018),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 7.0, z: 10.0)
            ),
            .init(
                name: "z3e1",
                position: .init(x: -0.011553861, y: -9.889167, z: -146.43015),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3e2z6z1",
                position: .init(x: 0.009905526, y: -35.106842, z: 126.63268),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 7.0, z: 10.0)
            ),
            .init(
                name: "z3e3",
                position: .init(x: -0.007611137, y: -33.594685, z: 123.47808),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}