//
//  BeadeauxS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct BeadeauxS: ZoneSceneMetadata {
    public let id = Zone.beadeauxS.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z6y1",
            position: .init(x: -51.99746, y: -11.656284, z: -106.25426),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z6y0z3f1",
            position: .init(x: -50.00364, y: -11.78, z: -111.502365),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 2.0, y: 4.0, z: 13.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}