//
//  BeadeauxS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct BeadeauxS: ZoneSceneMetadata {
        public let id = Zone.beadeauxS.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z451",
                position: .init(x: 218.468, y: -2.30248, z: -3.87133),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 7.0)
            ),
            .init(
                name: "z450z2w7",
                position: .init(x: 219.47, y: -4.4700084, z: 0.0378233),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 25.0, y: 10.0, z: 3.0)
            ),
            .init(
                name: "z453",
                position: .init(x: 282.2923, y: 2.497721, z: -17.907671),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 2.0, z: 3.0)
            ),
            .init(
                name: "z452z461",
                position: .init(x: 279.0022, y: 2.5337813, z: -18.078476),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 10.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z455",
                position: .init(x: 177.74481, y: 2.9180799, z: -238.57251),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 2.0, z: 3.0)
            ),
            .init(
                name: "z454z463",
                position: .init(x: 177.90724, y: 2.8067563, z: -241.37979),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 10.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z457",
                position: .init(x: -22.085651, y: 3.4540849, z: -80.149765),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 2.0, z: 3.0)
            ),
            .init(
                name: "z456z465",
                position: .init(x: -22.125996, y: 3.0420778, z: -82.9411),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 10.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z459",
                position: .init(x: 57.95162, y: 3.2041378, z: -359.42245),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 2.0, z: 3.0)
            ),
            .init(
                name: "z458z467",
                position: .init(x: 57.810143, y: 3.3930278, z: -362.4122),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 10.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z45b",
                position: .init(x: 93.17871, y: 2.2332547, z: -158.973),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 1.0, z: 2.0)
            ),
            .init(
                name: "z45az469",
                position: .init(x: 93.2082, y: 1.7340686, z: -162.22177),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 10.0, y: 8.0, z: 2.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}