//
//  BhaflauThickets.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct BhaflauThickets: ZoneSceneMetadata {
        public let id = Zone.bhaflauThickets.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z5s0z367",
                position: .init(x: 940.0013, y: -20.087929, z: -360.98578),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 12.0)
            ),
            .init(
                name: "z5s1",
                position: .init(x: 940.0, y: -17.591146, z: -357.75885),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5s2z369",
                position: .init(x: 700.01544, y: -28.00819, z: -685.0181),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 12.0)
            ),
            .init(
                name: "z5s3",
                position: .init(x: 700.00073, y: -25.7934, z: -688.18286),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5s4z3hb",
                position: .init(x: 180.00995, y: -12.267884, z: -145.0703),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 12.0)
            ),
            .init(
                name: "z5s5",
                position: .init(x: 179.9928, y: -9.753609, z: -147.95042),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5s6z3hd",
                position: .init(x: -740.0034, y: -20.211115, z: -518.9894),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 12.0)
            ),
            .init(
                name: "z5s7",
                position: .init(x: -740.0138, y: -17.602009, z: -521.8346),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5swz3hf",
                position: .init(x: -384.96826, y: -4.0194345, z: 860.0088),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 12.0)
            ),
            .init(
                name: "z5sx",
                position: .init(x: -381.5708, y: -1.773833, z: 859.9979),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5s8z36b",
                position: .init(x: 614.98096, y: -12.0284395, z: -379.98285),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 12.0)
            ),
            .init(
                name: "z5s9",
                position: .init(x: 618.3886, y: -9.799895, z: -380.00833),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5saz3hh",
                position: .init(x: 420.06476, y: -10.160898, z: -883.00183),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sb",
                position: .init(x: 419.98117, y: -8.6352, z: -879.7436),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5scz3hj",
                position: .init(x: -286.96823, y: -10.436476, z: -141.23582),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sd",
                position: .init(x: -290.52466, y: -8.761721, z: -141.25723),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5sez3hl",
                position: .init(x: 324.02234, y: -10.5144825, z: 60.323307),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sf",
                position: .init(x: 327.6084, y: -8.805339, z: 60.390884),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5sgz3hn",
                position: .init(x: -59.992123, y: -20.009321, z: 259.97723),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 20.0)
            ),
            .init(
                name: "z5sh",
                position: .init(x: -59.994, y: -17.649206, z: 263.4738),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 8.0)
            ),
            .init(
                name: "z5siz3hp",
                position: .init(x: -376.9559, y: -1.9880406, z: -297.5051),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sj",
                position: .init(x: -382.23297, y: -0.6533205, z: -296.31555),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5skz3hr",
                position: .init(x: -806.6386, y: -1.9408371, z: -259.52692),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sl",
                position: .init(x: -811.3283, y: -0.7582493, z: -258.4882),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5smz3ht",
                position: .init(x: -587.85315, y: -2.493394, z: 743.77893),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sn",
                position: .init(x: -583.6258, y: -0.88267565, z: 743.5799),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5soz3hv",
                position: .init(x: -344.13333, y: -3.208844, z: 488.58316),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sp",
                position: .init(x: -341.11832, y: -1.3370821, z: 484.06192),
                rotation: .init(x: 0.0, y: 1.1778138, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5sqz5t1",
                position: .init(x: 578.5627, y: 6.1982107, z: -492.00427),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sr",
                position: .init(x: 577.0332, y: 7.34315, z: -495.9998),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5ssz4o1",
                position: .init(x: -980.3927, y: 13.943332, z: -278.25604),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5st",
                position: .init(x: -980.1934, y: 14.913165, z: -282.86334),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5suz4o3",
                position: .init(x: -900.0787, y: 13.605657, z: -240.89615),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z5sv",
                position: .init(x: -900.33405, y: 14.849416, z: -245.43771),
                rotation: .init(x: 0.0, y: 1.8000364, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}