//
//  BhaflauThickets.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct BhaflauThickets: ZoneSceneMetadata {
        public let id = Zone.bhaflauThickets.rawValue
        public let name = "Bhaflau Thickets"
        public let lines: [ZoneLine] = [
            .init(
                name: "z1g0z1fn",
                position: .init(x: 300.0143, y: -15.684979, z: -32.19162),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 4.0, y: 15.0, z: 24.0)
            ),
            .init(
                name: "z1g1",
                position: .init(x: 299.99695, y: -13.369479, z: -27.997778),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 7.0)
            ),
            .init(
                name: "z1g2z1wl",
                position: .init(x: 439.98544, y: -14.67726, z: 419.97318),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z1g3",
                position: .init(x: 442.7654, y: -13.531465, z: 419.99866),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1g4z1wn",
                position: .init(x: 120.98595, y: -14.686002, z: 420.00717),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z1g5",
                position: .init(x: 118.65906, y: -13.566703, z: 419.9992),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1g6z1c3",
                position: .init(x: 437.97092, y: -12.998566, z: -40.005592),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 4.0, y: 15.0, z: 25.0)
            ),
            .init(
                name: "z1g7",
                position: .init(x: 432.986, y: -11.074716, z: -40.0412),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 11.0)
            ),
            .init(
                name: "z1g8z1t7",
                position: .init(x: -31.048084, y: -13.0836, z: -619.0611),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z1g9",
                position: .init(x: -33.516613, y: -12.769908, z: -619.263),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1gaz1t9",
                position: .init(x: -340.0174, y: -10.947399, z: -123.048256),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z1gb",
                position: .init(x: -340.01715, y: -9.553238, z: -119.994934),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1gcz1q5",
                position: .init(x: -41.05536, y: -7.021969, z: 300.01154),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z1gd",
                position: .init(x: -38.306305, y: -5.500003, z: 300.01782),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1gez1q7",
                position: .init(x: -556.94836, y: -3.356713, z: 99.989975),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z1gf",
                position: .init(x: -559.43884, y: -1.5000031, z: 100.02343),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1ggz20b",
                position: .init(x: 82.99929, y: -22.6294, z: 620.0222),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z1gh",
                position: .init(x: 79.99443, y: -21.578451, z: 619.9742),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1giz20d",
                position: .init(x: -398.01233, y: -11.075031, z: 20.00467),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z1gj",
                position: .init(x: -401.06464, y: -9.633395, z: 19.995125),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1gkz1v1",
                position: .init(x: -100.00627, y: -14.761104, z: -476.95715),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z1gl",
                position: .init(x: -100.00038, y: -13.500003, z: -479.51425),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}