//
//  CaedarvaMire.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct CaedarvaMire: ZoneSceneMetadata {
    public let id = Zone.caedarvaMire.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z420z413",
            position: .init(x: 321.74142, y: -128.39734, z: 379.97592),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 4.0, y: 10.0, z: 25.0)
        ),
        .init(
            name: "z421",
            position: .init(x: 317.842, y: -126.15806, z: 380.143),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z422z37h",
            position: .init(x: -260.29004, y: 111.15243, z: -363.57788),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 4.0, y: 12.0, z: 25.0)
        ),
        .init(
            name: "z423",
            position: .init(x: -259.64758, y: 113.72336, z: -358.8687),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}