//
//  CapeTeriggan.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct CapeTeriggan: ZoneSceneMetadata {
        public let id = Zone.capeTeriggan.rawValue
        public let name = "Cape Teriggan"
        public let lines: [ZoneLine] = [
            .init(
                name: "z784z795",
                position: .init(x: 260.446, y: -2.454026, z: -446.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 11.0, y: 8.0, z: 3.0)
            ),
            .init(
                name: "z785",
                position: .init(x: 260.044, y: -1.8437085, z: -441.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 4.0, z: 4.5)
            ),
            .init(
                name: "z782z793",
                position: .init(x: -100.208, y: -2.908374, z: -405.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 11.0, y: 8.0, z: 3.0)
            ),
            .init(
                name: "z780z791",
                position: .init(x: -379.572, y: -2.90837, z: -446.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 11.0, y: 8.0, z: 3.0)
            ),
            .init(
                name: "z783",
                position: .init(x: -100.836, y: -1.8783557, z: -399.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 4.0, z: 4.5)
            ),
            .init(
                name: "z781",
                position: .init(x: -379.759, y: -1.8077021, z: -441.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 4.0, z: 4.5)
            ),
            .init(
                name: "z787",
                position: .init(x: -540.076, y: 5.13453, z: -121.519),
                rotation: .init(x: 0.0, y: 1.6580628, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 5.0)
            ),
            .init(
                name: "z786z7h5",
                position: .init(x: -540.0, y: 4.5341554, z: -117.5),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 13.0, y: 8.0, z: 3.0)
            ),
            .init(
                name: "z788z7h3",
                position: .init(x: -117.0, y: 4.1938715, z: 419.984),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 9.0, z: 13.0)
            ),
            .init(
                name: "z789",
                position: .init(x: -121.0, y: 5.117809, z: 420.0),
                rotation: .init(x: 0.0, y: 3.2288592, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}