//
//  CapeTeriggan.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct CapeTeriggan: ZoneSceneMetadata {
        public let id = Zone.capeTeriggan.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z3g1",
                position: .init(x: -357.02438, y: 6.3857408, z: 139.42166),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3g0z3f5",
                position: .init(x: -360.0184, y: 3.9995716, z: 140.01204),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3g3",
                position: .init(x: -476.8533, y: 6.5026636, z: 59.4415),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3g2z3f7",
                position: .init(x: -480.01227, y: 4.2220087, z: 59.973083),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3g5",
                position: .init(x: -586.8399, y: 6.758133, z: -263.94626),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3g4z3f9",
                position: .init(x: -589.9753, y: 4.406907, z: -263.32135),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3g7",
                position: .init(x: -476.87772, y: 6.665288, z: -500.77396),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3g6z3fb",
                position: .init(x: -479.98648, y: 4.279119, z: -499.99716),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3g9",
                position: .init(x: -100.460754, y: -1.6277817, z: 255.80634),
                rotation: .init(x: 0.0, y: 0.8830767, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3g8z5p3",
                position: .init(x: -102.09777, y: -2.9304383, z: 258.74072),
                rotation: .init(x: 0.0, y: 0.96728706, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3gb",
                position: .init(x: 102.05551, y: -1.5707586, z: 344.13544),
                rotation: .init(x: 0.0, y: 2.650368, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3gaz5p1",
                position: .init(x: 105.100876, y: -3.3841026, z: 345.91156),
                rotation: .init(x: 0.0, y: 5.801314, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3gd",
                position: .init(x: 299.99677, y: -5.8375506, z: -622.9978),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z3gcz4f1",
                position: .init(x: 299.95538, y: -6.707598, z: -627.15094),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 9.0)
            ),
            .init(
                name: "z3gf",
                position: .init(x: 65.03527, y: -11.627788, z: -503.01752),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z3gez4f3",
                position: .init(x: 65.00284, y: -12.874139, z: -507.2058),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 9.0)
            ),
            .init(
                name: "z3gh",
                position: .init(x: 8.0036545, y: -11.638085, z: -503.05133),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z3ggz4f5",
                position: .init(x: 7.9712234, y: -12.884438, z: -507.23962),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 9.0)
            ),
            .init(
                name: "z3gl",
                position: .init(x: 343.00302, y: -11.649679, z: -168.009),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z3gkz4f7",
                position: .init(x: 347.38156, y: -12.750089, z: -168.00804),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 9.0)
            ),
            .init(
                name: "z3gj",
                position: .init(x: 342.9973, y: -11.6820965, z: -225.00673),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z3giz4f9",
                position: .init(x: 347.44464, y: -12.7969675, z: -225.01726),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 9.0)
            ),
            .init(
                name: "z3gn",
                position: .init(x: 380.79755, y: 6.3398104, z: 83.07419),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3gmz4gb",
                position: .init(x: 380.0222, y: 4.3206925, z: 80.02916),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}