//
//  CastleOztrojaS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct CastleOztrojaS: ZoneSceneMetadata {
        public let id = Zone.castleOztrojaS.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z3x1",
                position: .init(x: -161.49657, y: -21.977379, z: 19.9855),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.5, z: 5.0)
            ),
            .init(
                name: "z3x0z3w5",
                position: .init(x: -172.09065, y: -23.8736, z: 16.925068),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 5.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z3x3",
                position: .init(x: 219.94893, y: -86.031685, z: 19.489288),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.5, z: 5.0)
            ),
            .init(
                name: "z3x5",
                position: .init(x: 226.68796, y: -46.417046, z: 101.04465),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.5, z: 5.0)
            ),
            .init(
                name: "z3x2z3y1",
                position: .init(x: 225.67, y: -87.0011, z: 18.6199),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z3x4z3y3",
                position: .init(x: 232.903, y: -47.0285, z: 101.886),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z3x7",
                position: .init(x: 6.5871334, y: -22.08778, z: -107.076515),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.5, z: 5.0)
            ),
            .init(
                name: "z3x6z3y5",
                position: .init(x: 11.522606, y: -23.929611, z: -108.083664),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 15.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}