//
//  CastleZvahlKeep.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct CastleZvahlKeep: ZoneSceneMetadata {
        public let id = Zone.castleZvahlKeep.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z4u0z3h9",
                position: .init(x: -20.034498, y: -23.994743, z: -245.61131),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z4u1",
                position: .init(x: -20.007547, y: -22.161373, z: -242.02975),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4u2z351",
                position: .init(x: 20.417597, y: -23.369253, z: 280.0138),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z4u3",
                position: .init(x: 20.370358, y: -21.103941, z: 275.78198),
                rotation: .init(x: 0.0, y: 1.1192528, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}