//
//  CastleOztrojaS.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct CastleOztrojaS: ZoneSceneMetadata {
        public let id = Zone.castleOztrojaS.rawValue
        public let name = "Castle Oztroja [S]"
        public let lines: [ZoneLine] = [
            .init(
                name: "z7l6z7i1",
                position: .init(x: 404.0, y: 27.625734, z: 100.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z7l7",
                position: .init(x: 400.5, y: 27.856373, z: 100.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z7l2z7b3",
                position: .init(x: 484.0, y: -5.2820663, z: 140.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z7l0z7d3",
                position: .init(x: 500.0, y: 4.7582827, z: 404.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z7l8z7f1",
                position: .init(x: 340.0, y: -35.226562, z: 524.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z7l4z7e3",
                position: .init(x: 180.0, y: 25.1638, z: 37.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z7l3",
                position: .init(x: 480.5, y: -2.147447, z: 140.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z7l1",
                position: .init(x: 500.0, y: 7.9181457, z: 400.5),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z7l9",
                position: .init(x: 340.0, y: -32.11466, z: 520.5),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z7l5",
                position: .init(x: 180.0, y: 27.853535, z: 40.5),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}