//
//  CastleZvahlKeepS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct CastleZvahlKeepS: ZoneSceneMetadata {
    public let id = Zone.castleZvahlKeepS.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z6p0z381",
            position: .init(x: 126.748474, y: -9.457284, z: -39.976505),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z6p1",
            position: .init(x: 124.04296, y: -7.704227, z: -39.992203),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
        .init(
            name: "z6p2z6o5",
            position: .init(x: -94.20196, y: -1.7068938, z: -72.73815),
            rotation: .init(x: 0.0, y: 5.585054, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 16.0)
        ),
        .init(
            name: "z6p3",
            position: .init(x: -81.12114, y: 0.19030418, z: -67.625465),
            rotation: .init(x: 0.0, y: 0.34906584, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 5.0)
        ),
        .init(
            name: "zmrkzmrl",
            position: .init(x: -144.7271, y: -14.512944, z: 40.005333),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "zmrl",
            position: .init(x: -142.48686, y: -12.759887, z: 40.007084),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
        .init(
            name: "z6p4z6n3",
            position: .init(x: -60.724518, y: -7.1841636, z: 91.983376),
            rotation: .init(x: 0.0, y: 4.363323, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 16.0)
        ),
        .init(
            name: "z6p5",
            position: .init(x: -50.6412, y: -5.7762885, z: 79.2011),
            rotation: .init(x: 0.0, y: 0.95993125, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 5.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}