//
//  ChamberOfOracles.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct ChamberOfOracles: ZoneSceneMetadata {
        public let id = Zone.chamberOfOracles.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z0d0z0cd",
                position: .init(x: -119.954506, y: -123.47625, z: -619.9839),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 9.0, z: 13.0)
            ),
            .init(
                name: "z0d1",
                position: .init(x: -116.5989, y: -122.102844, z: -620.0104),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z0d2z0cf",
                position: .init(x: -158.30885, y: 176.93544, z: 500.0835),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 9.0, z: 13.0)
            ),
            .init(
                name: "z0d3",
                position: .init(x: -155.30241, y: 178.26082, z: 500.12094),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}