//
//  ChateauDOraguille.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct ChateauDOraguille: ZoneSceneMetadata {
        public let id = Zone.chateauDOraguille.rawValue
        public let name = "Chateau d'Oraguille"
        public let lines: [ZoneLine] = [
            .init(
                name: "z480z473",
                position: .init(x: -244.926, y: 10.383153, z: -99.9997),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z481",
                position: .init(x: -247.99792, y: 12.609081, z: -100.00798),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z482z475",
                position: .init(x: -285.0387, y: -3.6108358, z: 180.03206),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z483",
                position: .init(x: -288.0277, y: -1.4063916, z: 180.05449),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}