//
//  CloisterOfFrost.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct CloisterOfFrost: ZoneSceneMetadata {
    public let id = Zone.cloisterOfFrost.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z270z1h1",
            position: .init(x: 22.4394, y: 3.0484, z: -700.082),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 20.0)
        ),
        .init(
            name: "z271",
            position: .init(x: 25.964876, y: 2.5347729, z: -700.0088),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.5, y: 6.0, z: 6.0)
        ),
        .init(
            name: "z272z1h3",
            position: .init(x: 10.539478, y: -5.3377, z: -454.8945),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 18.0)
        ),
        .init(
            name: "z273",
            position: .init(x: 13.929695, y: -6.684216, z: -453.8361),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.5, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z274z1h5",
            position: .init(x: -257.5725, y: -5.0158205, z: -699.99524),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 18.0)
        ),
        .init(
            name: "z275",
            position: .init(x: -260.96127, y: -4.3699827, z: -699.9852),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.5, y: 6.0, z: 6.0)
        ),
        .init(
            name: "z276z1i1",
            position: .init(x: 140.0762, y: -14.2682, z: -37.4711),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z277",
            position: .init(x: 140.00706, y: -13.500003, z: -40.73565),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z278z1i3",
            position: .init(x: 474.54623, y: -30.73222, z: 140.05026),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z279",
            position: .init(x: 477.71347, y: -29.500004, z: 139.99),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27az1i5",
            position: .init(x: -499.97983, y: -3.438407, z: 121.51709),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27b",
            position: .init(x: -499.99887, y: -1.5000031, z: 118.32574),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27cz1i7",
            position: .init(x: -717.0742, y: 13.080281, z: -20.004276),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27d",
            position: .init(x: -719.993, y: 14.499997, z: -20.019905),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27ez1i9",
            position: .init(x: -699.9825, y: 5.971018, z: 118.53396),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27f",
            position: .init(x: -700.00964, y: 6.499997, z: 121.776665),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27gz1ib",
            position: .init(x: -637.3943, y: -18.773153, z: 339.97406),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27h",
            position: .init(x: -640.75916, y: -17.500004, z: 339.95486),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27iz1l1",
            position: .init(x: -438.50333, y: 8.63825, z: -499.96832),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27j",
            position: .init(x: -441.56598, y: 10.414023, z: -499.97443),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27kz201",
            position: .init(x: 340.00464, y: 1.4227273, z: -724.0253),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27l",
            position: .init(x: 339.99585, y: 2.499997, z: -721.28595),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27mz203",
            position: .init(x: 641.5782, y: -7.103291, z: 220.04335),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27n",
            position: .init(x: 644.7202, y: -5.6273084, z: 219.98886),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27oz205",
            position: .init(x: -460.01248, y: 0.8161156, z: -764.0019),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27p",
            position: .init(x: -460.00455, y: 2.4999971, z: -760.75555),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27qz207",
            position: .init(x: -357.5069, y: -2.670059, z: -300.01105),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27r",
            position: .init(x: -360.75925, y: -1.5000031, z: -300.03452),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27t",
            position: .init(x: -600.73883, y: 22.499996, z: -260.00317),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z27sz209",
            position: .init(x: -597.4916, y: 21.283712, z: -259.97733),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27uz261",
            position: .init(x: -539.98663, y: 9.084671, z: -556.03),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z27v",
            position: .init(x: -539.9957, y: 10.499997, z: -559.2072),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.5, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}