//
//  CloisterOfFrost.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct CloisterOfFrost: ZoneSceneMetadata {
        public let id = Zone.cloisterOfFrost.rawValue
        public let name = "Cloister of Frost"
        public let lines: [ZoneLine] = [
            .init(
                name: "z0h0z0g1",
                position: .init(x: -0.012528807, y: -4.10515, z: -295.991),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 11.0)
            ),
            .init(
                name: "z0h1",
                position: .init(x: -0.0392012, y: -4.083493, z: -293.74075),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}