//
//  CloisterOfGales.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct CloisterOfGales: ZoneSceneMetadata {
        public let id = Zone.cloisterOfGales.rawValue
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}