//
//  CloisterOfFlames.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct CloisterOfFlames: ZoneSceneMetadata {
        public let id = Zone.cloisterOfFlames.rawValue
        public let name = "Cloister of Flames"
        public let lines: [ZoneLine] = [
            .init(
                name: "z4w0z3f3",
                position: .init(x: 232.11896, y: -30.29049, z: 337.80643),
                rotation: .init(x: 0.0, y: 5.8059926, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z4w1",
                position: .init(x: 228.39078, y: -28.160427, z: 335.129),
                rotation: .init(x: 0.0, y: 2.514696, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4w2z701",
                position: .init(x: -60.56305, y: -4.395886, z: 415.56274),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z4w3",
                position: .init(x: -60.56624, y: -2.127215, z: 411.9756),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}