//
//  DangrufWadi.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct DangrufWadi: ZoneSceneMetadata {
    public let id = Zone.dangrufWadi.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z4vez2cl",
            position: .init(x: -555.01166, y: -20.913872, z: 99.99784),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4vf",
            position: .init(x: -558.93085, y: -18.095709, z: 99.9992),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z4vcz2cj",
            position: .init(x: -434.95886, y: -28.154371, z: 540.00244),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4vd",
            position: .init(x: -438.87805, y: -26.09127, z: 540.0038),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z4vaz2ch",
            position: .init(x: -300.00635, y: -28.083984, z: 115.01439),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4vb",
            position: .init(x: -300.01044, y: -26.099718, z: 119.191284),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z4v8z2cf",
            position: .init(x: -165.03099, y: -36.024033, z: 260.00336),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4v9",
            position: .init(x: -160.77583, y: -34.0766, z: 259.99786),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z4v4z2cb",
            position: .init(x: 340.0106, y: -52.11653, z: 324.9965),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4v5",
            position: .init(x: 339.99216, y: -50.075134, z: 321.0158),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z4v6z2cd",
            position: .init(x: 60.012344, y: -36.353996, z: 164.97939),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4v7",
            position: .init(x: 59.9895, y: -34.061676, z: 160.97311),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z4v0z2c7",
            position: .init(x: 420.00812, y: -60.0923, z: -122.00818),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4v1",
            position: .init(x: 420.03485, y: -58.114292, z: -119.50956),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z4v2z2c9",
            position: .init(x: 438.6471, y: -51.91435, z: -299.9914),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z4v3",
            position: .init(x: 436.61325, y: -49.300632, z: -300.01508),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}