//
//  DesuetiaEmpyrealParadox.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct DesuetiaEmpyrealParadox: ZoneSceneMetadata {
        public let id = Zone.desuetiaEmpyrealParadox.rawValue
        public let name = "Desuetia - Empyreal Paradox"
        public let lines: [ZoneLine] = [
            .init(
                name: "z2s1",
                position: .init(x: -125.88, y: -64.6373, z: 274.1),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 3.0, y: 5.0, z: 10.0)
            ),
            .init(
                name: "z2s0z6e3",
                position: .init(x: -119.06478, y: -65.70725, z: 280.92056),
                rotation: .init(x: 0.0, y: 2.3473742, z: 0.0),
                scale: .init(x: 8.700011, y: 10.0, z: 25.0)
            ),
            .init(
                name: "z2s3",
                position: .init(x: -172.18593, y: -64.59553, z: 379.998),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 3.0, y: 5.0, z: 8.0)
            ),
            .init(
                name: "z2s2z6f3",
                position: .init(x: -157.66562, y: -66.12367, z: 379.96048),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 8.700011, y: 10.0, z: 25.0)
            ),
            .init(
                name: "z2s4z2t1",
                position: .init(x: -11.696691, y: -53.64276, z: 140.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 8.700011, y: 10.0, z: 25.0)
            ),
            .init(
                name: "z2s5",
                position: .init(x: -24.4274, y: -53.107403, z: 140.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 3.0, y: 6.0, z: 10.0)
            ),
            .init(
                name: "z2s7",
                position: .init(x: 83.9129, y: -26.755512, z: -200.033),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z2s6z2t5",
                position: .init(x: 94.759636, y: -29.5313, z: -200.15277),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 8.70001, y: 30.0, z: 50.0)
            ),
            .init(
                name: "z2s8z3w1",
                position: .init(x: -740.57, y: -68.4778, z: 623.341),
                rotation: .init(x: 0.0, y: 4.1887903, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 20.0)
            ),
            .init(
                name: "z2s9",
                position: .init(x: -738.178, y: -67.17288, z: 619.3249),
                rotation: .init(x: 0.0, y: 0.9057945, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 6.0)
            ),
            .init(
                name: "z2sb",
                position: .init(x: -180.47342, y: -66.65012, z: 419.99545),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z2saz6f9",
                position: .init(x: -177.51637, y: -68.460945, z: 420.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 15.0)
            ),
            .init(
                name: "z2sd",
                position: .init(x: -559.9629, y: -7.062281, z: -602.4792),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z2scz2u1",
                position: .init(x: -560.4153, y: -10.328365, z: -613.176),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 8.70001, y: 30.0, z: 50.0)
            ),
            .init(
                name: "z2sf",
                position: .init(x: -712.74554, y: -40.500313, z: 18.407574),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 2.0, z: 3.0)
            ),
            .init(
                name: "z2sez4n3",
                position: .init(x: -716.8313, y: -42.251915, z: 18.19249),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 16.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}