//
//  DragonSAery.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct DragonSAery: ZoneSceneMetadata {
        public let id = Zone.dragonSAery.rawValue
        public let name = "Dragon's Aery"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}