//
//  DynamisXarcabard.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct DynamisXarcabard: ZoneSceneMetadata {
        public let id = Zone.dynamisXarcabard.rawValue
        public let name = "Dynamis - Xarcabard"
        public let lines: [ZoneLine] = [
            .init(
                name: "z6o0z373",
                position: .init(x: -249.08311, y: -11.6576, z: 199.97995),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z6o1",
                position: .init(x: -244.532, y: -10.7649, z: 199.974),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z6o2z6m3",
                position: .init(x: -114.594, y: -11.6542, z: 215.791),
                rotation: .init(x: 0.0, y: 5.061455, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 18.0)
            ),
            .init(
                name: "zmrezmrf",
                position: .init(x: 197.8051, y: -21.667278, z: 264.49506),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z6o4z6p3",
                position: .init(x: 230.555, y: -11.6576, z: 179.926),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z6o3",
                position: .init(x: -117.255035, y: -9.873576, z: 208.12677),
                rotation: .init(x: 0.0, y: 1.7453293, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 6.0)
            ),
            .init(
                name: "z6o5",
                position: .init(x: 219.815, y: -10.452718, z: 176.514),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 5.0)
            ),
            .init(
                name: "zmrf",
                position: .init(x: 197.71059, y: -20.774578, z: 261.85712),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}