//
//  DynamisQufim.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct DynamisQufim: ZoneSceneMetadata {
        public let id = Zone.dynamisQufim.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z020z2w9",
                position: .init(x: 0.78609395, y: -10.3123, z: -819.8506),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z021",
                position: .init(x: 6.5094285, y: -9.163069, z: -819.3333),
                rotation: .init(x: 0.0, y: 5.8468533, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z022z2wb",
                position: .init(x: -420.26367, y: -10.153435, z: -560.0765),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z023",
                position: .init(x: -419.79587, y: -8.94293, z: -554.553),
                rotation: .init(x: 0.0, y: 5.061455, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z024z6fb",
                position: .init(x: -479.70584, y: -14.3512535, z: 672.8509),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 45.0)
            ),
            .init(
                name: "z025",
                position: .init(x: -479.62054, y: -8.141342, z: 665.35016),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 8.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}