//
//  DynamisJeuno.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct DynamisJeuno: ZoneSceneMetadata {
        public let id = Zone.dynamisJeuno.rawValue
        public let name = "Dynamis - Jeuno"
        public let lines: [ZoneLine] = [
            .init(
                name: "z5d0z2u7",
                position: .init(x: -74.082, y: -4.1025753, z: 659.9972),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z5d1",
                position: .init(x: -76.8389, y: -1.6962774, z: 659.969),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z5d2z2u9",
                position: .init(x: 180.03441, y: 28.075499, z: 600.1123),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z5d3",
                position: .init(x: 179.90552, y: 30.349316, z: 596.60504),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z5d4z2ub",
                position: .init(x: -203.47615, y: -31.923763, z: -219.99483),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z5d5",
                position: .init(x: -200.3264, y: -29.607994, z: -219.84718),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}