//
//  DynamisQufim.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct DynamisQufim: ZoneSceneMetadata {
        public let id = Zone.dynamisQufim.rawValue
        public let name = "Dynamis - Qufim"
        public let lines: [ZoneLine] = [
            .init(
                name: "z1q0z1fp",
                position: .init(x: 122.076, y: -32.9748, z: -379.992),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1q1",
                position: .init(x: 119.514946, y: -32.000004, z: -379.98676),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1q2z1wp",
                position: .init(x: -19.9955, y: 16.655191, z: -442.01993),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1q3",
                position: .init(x: -20.007063, y: 17.999996, z: -439.5143),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1q4z1gd",
                position: .init(x: 522.04, y: -13.899956, z: 260.00955),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1q5",
                position: .init(x: 519.4862, y: -12.000803, z: 260.00803),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1q6z1gf",
                position: .init(x: -574.91907, y: -8.759148, z: -107.01602),
                rotation: .init(x: 0.0, y: 5.585054, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1q7",
                position: .init(x: -572.45197, y: -6.054196, z: -104.54174),
                rotation: .init(x: 0.0, y: 5.759587, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1q8z1p1",
                position: .init(x: 157.97408, y: -24.15904, z: 140.04697),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1q9",
                position: .init(x: 160.53955, y: -22.0012, z: 139.98799),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1qaz1p3",
                position: .init(x: 59.975365, y: -13.402293, z: 121.036354),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1qb",
                position: .init(x: 60.05219, y: -12.005013, z: 118.48154),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1qcz1p5",
                position: .init(x: -99.9744, y: -23.759644, z: -38.03021),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1qd",
                position: .init(x: -100.03049, y: -22.003069, z: -40.53908),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1qez1p7",
                position: .init(x: -197.98427, y: -4.090665, z: 99.981285),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1qf",
                position: .init(x: -200.56703, y: -2.0001092, z: 100.00106),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1qgz1p9",
                position: .init(x: -340.02737, y: -13.823507, z: -198.01004),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1qh",
                position: .init(x: -340.0284, y: -12.000488, z: -200.50323),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1qiz1pb",
                position: .init(x: -411.15414, y: -39.6918, z: 383.15216),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1qj",
                position: .init(x: -413.02383, y: -37.729507, z: 385.63004),
                rotation: .init(x: 0.0, y: 3.9269907, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1qkz1pd",
                position: .init(x: -539.98926, y: -44.291763, z: 398.05957),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1ql",
                position: .init(x: -539.997, y: -42.000305, z: 400.55078),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1qmz1pf",
                position: .init(x: -601.9574, y: -14.121992, z: 179.94795),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1qn",
                position: .init(x: -599.4226, y: -12.000004, z: 179.97134),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z1qoz1ph",
                position: .init(x: -539.9476, y: -13.9662, z: 81.99325),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 18.0)
            ),
            .init(
                name: "z1qp",
                position: .init(x: -539.97754, y: -12.000004, z: 79.53329),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}