//
//  DynamisTavnazia.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct DynamisTavnazia: ZoneSceneMetadata {
        public let id = Zone.dynamisTavnazia.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z3j0z3i3",
                position: .init(x: 361.02408, y: 22.10314, z: -60.00067),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z3j1",
                position: .init(x: 358.13412, y: 24.806446, z: -60.000706),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}