//
//  EastRonfaure.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct EastRonfaure: ZoneSceneMetadata {
        public let id = Zone.eastRonfaure.rawValue
        public let name = "East Ronfaure"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}