//
//  EasternAltepaDesert.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct EasternAltepaDesert: ZoneSceneMetadata {
        public let id = Zone.easternAltepaDesert.rawValue
        public let name = "Eastern Altepa Desert"
        public let lines: [ZoneLine] = [
            .init(
                name: "z0p0z0o1",
                position: .init(x: 572.4412, y: -19.4021, z: 282.6733),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 4.0, y: 10.0, z: 20.0)
            ),
            .init(
                name: "z0p1",
                position: .init(x: 567.624, y: -20.0002, z: 280.775),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.5, y: 6.0, z: 7.0)
            ),
            .init(
                name: "z0p2z0q5",
                position: .init(x: 602.5371, y: -2.850407, z: 19.97379),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z0p3",
                position: .init(x: 599.20544, y: -2.0131264, z: 20.143902),
                rotation: .init(x: 0.0, y: 3.281219, z: 0.0),
                scale: .init(x: 0.8, y: 3.0, z: 4.5)
            ),
            .init(
                name: "z0p4z0q7",
                position: .init(x: 642.4318, y: 21.0942, z: -220.02211),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z0p5",
                position: .init(x: 638.8316, y: 21.740187, z: -220.49413),
                rotation: .init(x: 0.0, y: 2.8797932, z: 0.0),
                scale: .init(x: 0.8, y: 3.0, z: 4.5)
            ),
            .init(
                name: "z0p7",
                position: .init(x: 53.2264, y: -25.6708, z: 739.997),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 0.8, y: 3.0, z: 3.5)
            ),
            .init(
                name: "z0p6z0s1",
                position: .init(x: 61.062904, y: -27.67439, z: 739.9967),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}