//
//  EasternAltepaDesert.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct EasternAltepaDesert: ZoneSceneMetadata {
    public let id = Zone.easternAltepaDesert.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z090z339",
            position: .init(x: 404.92465, y: -11.875921, z: -20.007744),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z091",
            position: .init(x: 402.47302, y: -10.329934, z: -19.98356),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z092z33b",
            position: .init(x: 220.05292, y: -11.91635, z: -274.9516),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z093",
            position: .init(x: 220.01074, y: -10.344015, z: -277.49014),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z094z33d",
            position: .init(x: 180.01295, y: -11.992367, z: 234.99626),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z095",
            position: .init(x: 179.977, y: -10.339751, z: 237.494),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z096z33f",
            position: .init(x: -235.01088, y: 4.119215, z: -259.9847),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z097",
            position: .init(x: -237.47171, y: 5.6946588, z: -259.99454),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z098z33h",
            position: .init(x: -179.98923, y: -11.937845, z: -85.020226),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z099",
            position: .init(x: -179.98604, y: -10.417356, z: -82.49549),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09az33j",
            position: .init(x: -299.99884, y: -11.982715, z: 194.992),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09b",
            position: .init(x: -299.9954, y: -10.320812, z: 197.50443),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09cz09d",
            position: .init(x: 14.977579, y: -2.9667718, z: 230.00026),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09f",
            position: .init(x: 12.055495, y: -1.9812697, z: 229.96912),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09ez09f",
            position: .init(x: 135.03929, y: -3.5552464, z: 70.03268),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09d",
            position: .init(x: 132.03857, y: -2.15899, z: 69.99759),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09gz09h",
            position: .init(x: 135.05019, y: -3.19613, z: 50.03777),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09j",
            position: .init(x: 131.99442, y: -2.1653306, z: 50.013725),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09iz09j",
            position: .init(x: -50.00515, y: -3.1408439, z: 214.95175),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09h",
            position: .init(x: -49.986034, y: -2.0271811, z: 211.9942),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09kz09l",
            position: .init(x: -69.99725, y: -3.6930532, z: 214.95044),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09l",
            position: .init(x: 30.00916, y: -1.7268119, z: 147.99261),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09mz09n",
            position: .init(x: 30.032799, y: -3.380743, z: 144.97934),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09n",
            position: .init(x: -70.00239, y: -2.1230006, z: 211.97533),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09oz09p",
            position: .init(x: 14.955461, y: -3.03348, z: 209.98892),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09p",
            position: .init(x: 10.013063, y: -1.7450562, z: 147.99629),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09qz09r",
            position: .init(x: 10.013063, y: -3.4392865, z: 144.96869),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09r",
            position: .init(x: 11.976637, y: -1.9304051, z: 210.01907),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09sz09t",
            position: .init(x: 15.028647, y: -3.0267475, z: 70.04534),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09t",
            position: .init(x: 11.971304, y: -1.9487579, z: -49.977),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09uz09v",
            position: .init(x: 14.984222, y: -3.0314827, z: -50.011215),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09v",
            position: .init(x: 12.007917, y: -1.9283861, z: 69.99952),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09wz09x",
            position: .init(x: 15.027325, y: -3.0762784, z: 50.01558),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09x",
            position: .init(x: 12.004456, y: -1.9643519, z: -70.00916),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z09yz09z",
            position: .init(x: 15.02161, y: -3.0237164, z: -69.99881),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z09z",
            position: .init(x: 12.0114975, y: -1.9555129, z: 49.98561),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi90zi91",
            position: .init(x: -150.01854, y: -3.1210358, z: 50.043167),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi91",
            position: .init(x: -29.956053, y: -1.9034956, z: 212.52069),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi92zi93",
            position: .init(x: -29.994467, y: -3.4395454, z: 210.00032),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi93",
            position: .init(x: -150.00648, y: -1.9816368, z: 47.486206),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi94zi95",
            position: .init(x: -169.95981, y: -3.3608534, z: 9.953483),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi95",
            position: .init(x: -52.472427, y: -2.021836, z: 170.00844),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi96zi97",
            position: .init(x: -50.00089, y: -3.156483, z: 169.95546),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi97",
            position: .init(x: -167.51366, y: -2.009407, z: 9.98679),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi98zi99",
            position: .init(x: -109.99998, y: -3.418073, z: 30.007496),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi99",
            position: .init(x: 12.485677, y: -1.9628158, z: 189.9818),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi9azi9b",
            position: .init(x: 10.01348, y: -3.3502662, z: 189.9818),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi9b",
            position: .init(x: -112.499725, y: -1.9626176, z: 30.015018),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi9czi9d",
            position: .init(x: -29.991753, y: -3.0177824, z: -70.015274),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi9d",
            position: .init(x: 90.034164, y: -1.9797696, z: 52.50436),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi9ezi9f",
            position: .init(x: 89.97405, y: -3.2038574, z: 49.989716),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi9f",
            position: .init(x: -30.180632, y: -1.5000031, z: -67.08199),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi9gz0a1",
            position: .init(x: -60.0, y: 36.986107, z: 1.07766),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi9h",
            position: .init(x: -60.0, y: 38.5038, z: 4.9808164),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "zi9iz0a3",
            position: .init(x: 20.0, y: 36.7687, z: -15.0734),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "zi9j",
            position: .init(x: 20.0, y: 38.499996, z: -11.0052),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}