//
//  EschaZiTah.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct EschaZiTah: ZoneSceneMetadata {
        public let id = Zone.eschaZiTah.rawValue
        public let name = "Escha - Zi'Tah"
        public let lines: [ZoneLine] = [
            .init(
                name: "z2u0z2sd",
                position: .init(x: -558.56854, y: -7.04904, z: 688.0494),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 35.0, y: 20.0, z: 3.0)
            ),
            .init(
                name: "z2u1",
                position: .init(x: -559.978, y: -3.0978293, z: 680.592),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 10.0)
            ),
            .init(
                name: "z2u2z2w1",
                position: .init(x: 801.8306, y: 24.325665, z: -37.617672),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 35.0, y: 20.0, z: 3.0)
            ),
            .init(
                name: "z2u3",
                position: .init(x: 795.1184, y: 28.22133, z: -39.978325),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 13.0)
            ),
            .init(
                name: "z2u4z2v3",
                position: .init(x: 160.16922, y: 24.325665, z: -764.00726),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 35.0, y: 20.0, z: 3.0)
            ),
            .init(
                name: "z2u5",
                position: .init(x: 159.98936, y: 28.405508, z: -760.1905),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 13.0)
            ),
            .init(
                name: "z2u6z5d1",
                position: .init(x: -276.649, y: 20.594193, z: 99.6175),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 20.0, y: 10.0, z: 3.0)
            ),
            .init(
                name: "z2u7",
                position: .init(x: -272.11804, y: 21.714613, z: 98.858765),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z2u8z5d3",
                position: .init(x: -60.125137, y: 27.23093, z: 148.0014),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 20.0, y: 10.0, z: 3.0)
            ),
            .init(
                name: "z2u9",
                position: .init(x: -59.41256, y: 28.698948, z: 151.63353),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z2uaz5d5",
                position: .init(x: 59.00074, y: 36.45863, z: -312.49298),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 20.0, y: 10.0, z: 3.0)
            ),
            .init(
                name: "z2ub",
                position: .init(x: 60.019997, y: 37.761433, z: -316.18274),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}