//
//  Feretory.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct Feretory: ZoneSceneMetadata {
    public let id = Zone.feretory.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z300z2y7",
            position: .init(x: 101.19872, y: -77.59457, z: -611.9824),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 25.0, y: 15.0, z: 3.0)
        ),
        .init(
            name: "z301",
            position: .init(x: 101.543, y: -75.45259, z: -607.531),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z302z311",
            position: .init(x: 520.09973, y: 26.451286, z: 752.858),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 25.0, y: 15.0, z: 3.0)
        ),
        .init(
            name: "z303",
            position: .init(x: 521.922, y: 28.361004, z: 747.85),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 8.0)
        ),
        .init(
            name: "z304z2v1",
            position: .init(x: -160.469, y: 64.88281, z: 887.73114),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 25.0, y: 15.0, z: 3.0)
        ),
        .init(
            name: "z305",
            position: .init(x: -160.124, y: 68.2504, z: 883.812),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 8.0)
        ),
        .init(
            name: "z306z5g1",
            position: .init(x: 707.6455, y: 16.174389, z: 217.54482),
            rotation: .init(x: 0.0, y: 1.3962634, z: 0.0),
            scale: .init(x: 10.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "z307",
            position: .init(x: 703.53235, y: 17.043537, z: 216.50249),
            rotation: .init(x: 0.0, y: 2.792527, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}