//
//  FortKarugoNarugoS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct FortKarugoNarugoS: ZoneSceneMetadata {
    public let id = Zone.fortKarugoNarugoS.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z1l0z27j",
            position: .init(x: -43.033848, y: -11.861744, z: -260.0097),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z1l1",
            position: .init(x: -39.998085, y: -9.873147, z: -260.18192),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.5, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z1l2z1id",
            position: .init(x: 64.00873, y: -11.442844, z: -96.99426),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z1l3",
            position: .init(x: 64.00665, y: -9.280873, z: -99.9876),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.5, y: 4.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}