//
//  FortGhelsba.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct FortGhelsba: ZoneSceneMetadata {
        public let id = Zone.fortGhelsba.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z5v1",
                position: .init(x: 564.77563, y: 34.296963, z: 500.81946),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5v0z4gd",
                position: .init(x: 561.347, y: 33.017624, z: 499.99893),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 12.0)
            ),
            .init(
                name: "z5v3",
                position: .init(x: -499.99567, y: 14.221533, z: -440.78836),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5v2z4gf",
                position: .init(x: -500.02594, y: 12.5432, z: -437.11356),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 13.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}