//
//  FullMoonFountain.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct FullMoonFountain: ZoneSceneMetadata {
    public let id = Zone.fullMoonFountain.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z5g0z307",
            position: .init(x: 44.028015, y: -71.118454, z: -340.1201),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 14.0, y: 10.0, z: 1.0)
        ),
        .init(
            name: "z5g1",
            position: .init(x: 45.98207, y: -69.65094, z: -340.09354),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z5g2z0b5",
            position: .init(x: 100.20437, y: -63.5617, z: -240.49373),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 14.0, y: 10.0, z: 1.0)
        ),
        .init(
            name: "z5g3",
            position: .init(x: 100.006546, y: -61.63025, z: -237.44144),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}