//
//  Giddeus.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct Giddeus: ZoneSceneMetadata {
        public let id = Zone.giddeus.rawValue
        public let name = "Giddeus"
        public let lines: [ZoneLine] = [
            .init(
                name: "z6f0z6e5",
                position: .init(x: -0.10749439, y: -7.067552, z: -36.133457),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 12.0, y: 15.0, z: 3.0)
            ),
            .init(
                name: "z6f2z2s3",
                position: .init(x: -252.15808, y: 1.6625082, z: 43.91271),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 12.0, y: 15.0, z: 3.0)
            ),
            .init(
                name: "z6f6z6g1",
                position: .init(x: -123.50965, y: 8.289007, z: 270.5164),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 8.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z6f1",
                position: .init(x: 0.00747282, y: -2.314896, z: -32.4696),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 6.0)
            ),
            .init(
                name: "z6f3",
                position: .init(x: -248.89334, y: 4.640112, z: 44.025784),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z6f8z2sb",
                position: .init(x: -238.70206, y: -9.433233, z: 105.96106),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 12.0, y: 15.0, z: 3.0)
            ),
            .init(
                name: "z6f9",
                position: .init(x: -234.393, y: -5.7409234, z: 106.00922),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z6f7",
                position: .init(x: -125.375, y: 10.370675, z: 268.64),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "zmr2zmr3",
                position: .init(x: 134.995, y: -7.0675507, z: -8.43869),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 14.0, y: 15.0, z: 3.0)
            ),
            .init(
                name: "zmr3",
                position: .init(x: 132.76413, y: -2.3197541, z: -6.1784897),
                rotation: .init(x: 0.0, y: 3.926991, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z6faz025",
                position: .init(x: -123.566, y: 9.96575, z: 192.841),
                rotation: .init(x: 0.0, y: 5.4977875, z: 0.0),
                scale: .init(x: 6.0, y: 4.0, z: 2.0)
            ),
            .init(
                name: "z6fb",
                position: .init(x: -127.47153, y: 10.499997, z: 195.47818),
                rotation: .init(x: 0.0, y: 3.9269907, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}