//
//  GrandPalaceOfHuXzoi.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct GrandPalaceOfHuXzoi: ZoneSceneMetadata {
    public let id = Zone.grandPalaceOfHuXzoi.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z7d0z7h1",
            position: .init(x: 580.0, y: -11.650384, z: -482.0),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 3.0, y: 9.0, z: 12.0)
        ),
        .init(
            name: "z7d1",
            position: .init(x: 580.522, y: -10.035329, z: -477.705),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z7d2z7l1",
            position: .init(x: -540.0, y: -27.865593, z: -405.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 9.0, z: 12.0)
        ),
        .init(
            name: "z7d3",
            position: .init(x: -540.237, y: -25.793592, z: -399.5),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}