//
//  GrandPalaceOfHuXzoi.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct GrandPalaceOfHuXzoi: ZoneSceneMetadata {
        public let id = Zone.grandPalaceOfHuXzoi.rawValue
        public let name = "Grand Palace of Hu'Xzoi"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}