//
//  GraubergS.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct GraubergS: ZoneSceneMetadata {
        public let id = Zone.graubergS.rawValue
        public let name = "Grauberg [S]"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}