//
//  GusgenMines.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct GusgenMines: ZoneSceneMetadata {
        public let id = Zone.gusgenMines.rawValue
        public let name = "Gusgen Mines"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}