//
//  GustavTunnel.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct GustavTunnel: ZoneSceneMetadata {
        public let id = Zone.gustavTunnel.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z5i1",
                position: .init(x: -362.44635, y: -12.747492, z: -179.9915),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z5i0z395",
                position: .init(x: -370.00372, y: -15.322451, z: -180.8218),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z5i3",
                position: .init(x: 474.6285, y: -31.203485, z: -259.09085),
                rotation: .init(x: 0.0, y: 3.574255, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z5i2z3a5",
                position: .init(x: 479.99326, y: -33.64191, z: -259.9759),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z5i5",
                position: .init(x: -140.24632, y: -12.738494, z: 160.70906),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z5i4z071",
                position: .init(x: -140.3313, y: -14.164512, z: 164.23997),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 15.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}