//
//  HallOfTheGods.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct HallOfTheGods: ZoneSceneMetadata {
        public let id = Zone.hallOfTheGods.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z4i0z4h3",
                position: .init(x: 64.94722, y: -4.505412, z: -20.005339),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z4i1",
                position: .init(x: 62.014496, y: -1.906787, z: -19.988503),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4i2z4l1",
                position: .init(x: -559.607, y: -72.73054, z: 59.95915),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 10.0)
            ),
            .init(
                name: "z4i3",
                position: .init(x: -555.99646, y: -71.69061, z: 59.9894),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}