//
//  HazhalmTestingGrounds.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct HazhalmTestingGrounds: ZoneSceneMetadata {
        public let id = Zone.hazhalmTestingGrounds.rawValue
        public let name = "Hazhalm Testing Grounds"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}