//
//  InnerHorutotoRuins.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct InnerHorutotoRuins: ZoneSceneMetadata {
        public let id = Zone.innerHorutotoRuins.rawValue
        public let name = "Inner Horutoto Ruins"
        public let lines: [ZoneLine] = [
            .init(
                name: "z0i0z0j1",
                position: .init(x: 20.0, y: -2.1744761, z: 59.998074),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 8.0)
            ),
            .init(
                name: "z0i1",
                position: .init(x: 20.0, y: -2.1003761, z: 63.030827),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}