//
//  InnerHorutotoRuins.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct InnerHorutotoRuins: ZoneSceneMetadata {
    public let id = Zone.innerHorutotoRuins.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z4g0z4fb",
            position: .init(x: 459.97134, y: -17.21174, z: 240.0101),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z4g1",
            position: .init(x: 460.00323, y: -15.530792, z: 236.89287),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z4g2z4fd",
            position: .init(x: 19.987047, y: 2.5684993, z: 40.05345),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z4g3",
            position: .init(x: 20.018938, y: 4.6812983, z: 36.93623),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z4g4z4ff",
            position: .init(x: -220.004, y: 2.8175235, z: -79.96509),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z4g5",
            position: .init(x: -219.9721, y: 4.7379746, z: -83.08232),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z4g6z4fh",
            position: .init(x: -40.012054, y: 2.7977479, z: 20.04361),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z4g7",
            position: .init(x: -36.017773, y: 5.194375, z: 19.986258),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z4g8z4j3",
            position: .init(x: -104.914, y: 42.06028, z: 55.9596),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 9.0, z: 14.0)
        ),
        .init(
            name: "z4g9",
            position: .init(x: -100.84782, y: 43.910404, z: 55.405178),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 5.0)
        ),
        .init(
            name: "z4gaz3gn",
            position: .init(x: 259.965, y: -17.2953, z: 323.041),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 13.0)
        ),
        .init(
            name: "z4gb",
            position: .init(x: 260.01886, y: -15.727599, z: 319.87057),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z4gcz5v1",
            position: .init(x: 200.04652, y: 32.81335, z: -60.078712),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z4gd",
            position: .init(x: 196.42067, y: 34.594696, z: -60.31893),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z4gez5v3",
            position: .init(x: 179.97102, y: 13.097593, z: -160.01257),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z4gf",
            position: .init(x: 179.83698, y: 13.394195, z: -157.07382),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}