//
//  JugnerForest.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct JugnerForest: ZoneSceneMetadata {
    public let id = Zone.jugnerForest.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z3h0z363",
            position: .init(x: 378.6767, y: 7.0812654, z: -12.102691),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 14.0)
        ),
        .init(
            name: "z3h1",
            position: .init(x: 379.25598, y: 6.953589, z: -7.993388),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3h2z4t5",
            position: .init(x: 680.2784, y: 12.371163, z: -100.20091),
            rotation: .init(x: 0.0, y: 3.350325, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 14.0)
        ),
        .init(
            name: "z3h3",
            position: .init(x: 676.28015, y: 12.741589, z: -99.42502),
            rotation: .init(x: 0.0, y: 3.3844047, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3h4z6v1",
            position: .init(x: 420.2837, y: 4.910671, z: 363.91202),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 14.0)
        ),
        .init(
            name: "z3h5",
            position: .init(x: 419.96933, y: 5.699345, z: 359.80176),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3h6z365",
            position: .init(x: -114.44335, y: -2.5754445, z: -500.3604),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 14.0)
        ),
        .init(
            name: "z3h7",
            position: .init(x: -118.83706, y: -2.6457794, z: -500.49933),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3h8z4u1",
            position: .init(x: -19.83242, y: 12.930556, z: 443.82645),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 14.0)
        ),
        .init(
            name: "z3h9",
            position: .init(x: -19.901442, y: 13.606736, z: 440.05847),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3haz5s5",
            position: .init(x: 179.94218, y: 14.683637, z: -285.08734),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 14.0)
        ),
        .init(
            name: "z3hb",
            position: .init(x: 179.98845, y: 16.042866, z: -281.51108),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hcz5s7",
            position: .init(x: -739.9792, y: -13.356148, z: -765.0118),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hd",
            position: .init(x: -740.00024, y: -11.966528, z: -761.5368),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hez5sx",
            position: .init(x: -280.0095, y: 14.344965, z: 299.98526),
            rotation: .init(x: 0.0, y: 6.278507, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hf",
            position: .init(x: -283.00323, y: 15.912754, z: 299.96426),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hgz5sb",
            position: .init(x: -138.75838, y: 8.079364, z: -328.0255),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hh",
            position: .init(x: -138.78416, y: 8.934287, z: -332.04935),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hiz5sd",
            position: .init(x: -329.0709, y: 8.361147, z: -221.28708),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hj",
            position: .init(x: -325.23413, y: 8.7771845, z: -220.85236),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hkz5sf",
            position: .init(x: 223.95172, y: 14.189249, z: 12.710847),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hl",
            position: .init(x: 220.07132, y: 14.204145, z: 13.229594),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hmz5sh",
            position: .init(x: -19.983004, y: 22.143831, z: 204.96387),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hn",
            position: .init(x: -20.000914, y: 23.950563, z: 201.72485),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hoz5sj",
            position: .init(x: -848.5055, y: 7.984681, z: -541.01855),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hp",
            position: .init(x: -844.7344, y: 8.842135, z: -540.74854),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hqz5sl",
            position: .init(x: -888.0215, y: 7.199156, z: -421.2321),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hr",
            position: .init(x: -883.96936, y: 8.776338, z: -420.90997),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3hsz5sn",
            position: .init(x: -375.96915, y: 14.525845, z: 186.97104),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3ht",
            position: .init(x: -379.06888, y: 14.444252, z: 186.90074),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z3huz5sp",
            position: .init(x: -492.82944, y: 13.821687, z: 97.9239),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z3hv",
            position: .init(x: -492.9196, y: 13.868817, z: 101.98909),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}