//
//  LabyrinthOfOnzozo.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct LabyrinthOfOnzozo: ZoneSceneMetadata {
    public let id = Zone.labyrinthOfOnzozo.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z2v0z305",
            position: .init(x: 919.212, y: -4.63902, z: -440.003),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 32.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "z2v1",
            position: .init(x: 919.9891, y: -2.1012096, z: -436.81622),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 6.0)
        ),
        .init(
            name: "z2v2z2u5",
            position: .init(x: 758.3229, y: -11.991554, z: 412.1683),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 32.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "z2v3",
            position: .init(x: 760.0692, y: -9.948778, z: 409.2689),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 6.0)
        ),
        .init(
            name: "z2v4z6w1",
            position: .init(x: 60.003075, y: -7.5288467, z: -154.53667),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 32.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "z2v5",
            position: .init(x: 60.989357, y: -4.898416, z: -151.00076),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z2v6z5w3",
            position: .init(x: -767.8662, y: -11.955723, z: 18.376093),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 15.0, y: 10.0, z: 2.0)
        ),
        .init(
            name: "z2v7",
            position: .init(x: -772.0179, y: -9.8727455, z: 19.100697),
            rotation: .init(x: 0.0, y: 3.3565474, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}