//
//  Leafallia.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct Leafallia: ZoneSceneMetadata {
        public let id = Zone.leafallia.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z1v0z1gl",
                position: .init(x: 340.66797, y: -16.868433, z: -160.00708),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 15.0)
            ),
            .init(
                name: "z1v1",
                position: .init(x: 340.38306, y: -13.625264, z: -157.44662),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}