//
//  LeujaoamSanctum.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct LeujaoamSanctum: ZoneSceneMetadata {
        public let id = Zone.leujaoamSanctum.rawValue
        public let name = "Leujaoam Sanctum"
        public let lines: [ZoneLine] = [
            .init(
                name: "z110z0x3",
                position: .init(x: 580.0, y: -2.83971, z: -4.34214),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z111",
                position: .init(x: 580.0, y: -1.49998, z: 4.45249),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}