//
//  LeujaoamSanctum.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct LeujaoamSanctum: ZoneSceneMetadata {
    public let id = Zone.leujaoamSanctum.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z470z3b5",
            position: .init(x: -242.00217, y: -3.9553611, z: -20.019106),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z471",
            position: .init(x: -239.44745, y: -1.813427, z: -19.98049),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z472z481",
            position: .init(x: -165.50534, y: 19.886766, z: -140.0272),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z473",
            position: .init(x: -162.89485, y: 22.1363, z: -139.9229),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z474z483",
            position: .init(x: -295.0898, y: -4.001269, z: 180.00005),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z475",
            position: .init(x: -292.00925, y: -1.88615, z: 179.9937),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}