//
//  Lobby.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct Lobby: ZoneSceneMetadata {
        public let id = Zone.lobby.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z3f0z6y1",
                position: .init(x: -241.934, y: -2.1355078, z: 531.924),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 16.0)
            ),
            .init(
                name: "z3f1",
                position: .init(x: -239.661, y: -1.5749267, z: 528.069),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 5.0)
            ),
            .init(
                name: "z3f2z4w1",
                position: .init(x: -640.01984, y: 12.239753, z: -419.94916),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3f3",
                position: .init(x: -636.328, y: 14.479659, z: -420.062),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3f4z3g1",
                position: .init(x: 120.00386, y: 4.2668576, z: 99.99399),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3f5",
                position: .init(x: 116.82476, y: 6.612745, z: 100.00007),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3f6z3g3",
                position: .init(x: 119.984184, y: 4.2668576, z: 19.98318),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3f7",
                position: .init(x: 116.805084, y: 6.612745, z: 19.98926),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3f8z3g5",
                position: .init(x: 119.99251, y: 4.2668576, z: -299.97485),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3f9",
                position: .init(x: 116.81341, y: 6.427894, z: -299.96878),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3faz3g7",
                position: .init(x: 111.599686, y: 4.2668576, z: -457.3259),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3fb",
                position: .init(x: 108.18944, y: 6.3749857, z: -456.8893),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3fcz5p7",
                position: .init(x: 420.02524, y: 16.096088, z: 480.0345),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z3fd",
                position: .init(x: 420.00482, y: 18.650372, z: 476.7869),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}