//
//  LowerDelkfuttSTower.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct LowerDelkfuttSTower: ZoneSceneMetadata {
        public let id = Zone.lowerDelkfuttSTower.rawValue
        public let name = "Lower Delkfutt's Tower"
        public let lines: [ZoneLine] = [
            .init(
                name: "z5h0z329",
                position: .init(x: 380.064, y: -35.3323, z: 6.945321),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 12.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z5h1",
                position: .init(x: 380.61725, y: -34.61046, z: 4.5811896),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5h2z32b",
                position: .init(x: 87.46854, y: -3.5898285, z: 380.54514),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 12.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z5h3",
                position: .init(x: 84.74062, y: -2.4710696, z: 379.57416),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}