//
//  LufaiseMeadows.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct LufaiseMeadows: ZoneSceneMetadata {
        public let id = Zone.lufaiseMeadows.rawValue
        public let name = "Lufaise Meadows"
        public let lines: [ZoneLine] = [
            .init(
                name: "z260z27v",
                position: .init(x: 654.6697, y: -274.2655, z: -107.74148),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z261",
                position: .init(x: 652.1739, y: -272.6318, z: -104.92011),
                rotation: .init(x: 0.0, y: 3.752458, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}