//
//  Mamook.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct Mamook: ZoneSceneMetadata {
        public let id = Zone.mamook.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z7t0z7f3",
                position: .init(x: 19.3552, y: -5.0, z: -43.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 12.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}