//
//  MamoolJaTrainingGrounds.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct MamoolJaTrainingGrounds: ZoneSceneMetadata {
        public let id = Zone.mamoolJaTrainingGrounds.rawValue
        public let name = "Mamool Ja Training Grounds"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}