//
//  MeriphataudMountainsS.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct MeriphataudMountainsS: ZoneSceneMetadata {
        public let id = Zone.meriphataudMountainsS.rawValue
        public let name = "Meriphataud Mountains [S]"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}