//
//  MeriphataudMountainsS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct MeriphataudMountainsS: ZoneSceneMetadata {
    public let id = Zone.meriphataudMountainsS.rawValue
    public let lines: [ZoneLine] = [
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}