//
//  Mhaura.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct Mhaura: ZoneSceneMetadata {
        public let id = Zone.mhaura.rawValue
        public let name = "Mhaura"
        public let lines: [ZoneLine] = [
            .init(
                name: "z3u0z3t3",
                position: .init(x: 414.9506, y: -16.60771, z: -19.994535),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z3u1",
                position: .init(x: 412.0199, y: -13.611209, z: -19.963829),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3u2z4b1",
                position: .init(x: -185.02565, y: -39.49678, z: 20.000006),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z3u3",
                position: .init(x: -181.96869, y: -35.541588, z: 19.994799),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}