//
//  MiddleDelkfuttSTower.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct MiddleDelkfuttSTower: ZoneSceneMetadata {
        public let id = Zone.middleDelkfuttSTower.rawValue
        public let name = "Middle Delkfutt's Tower"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}