//
//  MineShaft2716.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct MineShaft2716: ZoneSceneMetadata {
    public let id = Zone.mineShaft2716.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z7a1",
            position: .init(x: 374.34723, y: 7.8196273, z: 460.167),
            rotation: .init(x: 0.0, y: 2.7925267, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z7a0z7g5",
            position: .init(x: 380.358, y: 9.427605, z: 462.21),
            rotation: .init(x: 0.0, y: 1.0471976, z: 0.0),
            scale: .init(x: 13.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z7a3",
            position: .init(x: 99.5635, y: 7.78992, z: -66.5152),
            rotation: .init(x: 0.0, y: 1.3089969, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z7a2z7g7",
            position: .init(x: 99.14749, y: 8.835716, z: -61.627945),
            rotation: .init(x: 0.0, y: 6.0213857, z: 0.0),
            scale: .init(x: 13.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z7a5",
            position: .init(x: -355.48, y: 9.5428505, z: 301.098),
            rotation: .init(x: 0.0, y: 0.2617994, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z7a4z7k3",
            position: .init(x: -360.06125, y: 11.097472, z: 305.12027),
            rotation: .init(x: 0.0, y: 2.0071287, z: 0.0),
            scale: .init(x: 13.0, y: 8.0, z: 2.0)
        ),
        .init(
            name: "z7a7",
            position: .init(x: -455.87997, y: 8.441098, z: -300.68344),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z7a6z7k1",
            position: .init(x: -460.97696, y: 9.466822, z: -302.50754),
            rotation: .init(x: 0.0, y: 1.3089969, z: 0.0),
            scale: .init(x: 13.0, y: 8.0, z: 2.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}