//
//  MogGarden.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct MogGarden: ZoneSceneMetadata {
        public let id = Zone.mogGarden.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z200z27l",
                position: .init(x: -20.0, y: -10.0, z: 840.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z201",
                position: .init(x: -20.0, y: -6.5001454, z: 835.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z202z27n",
                position: .init(x: 320.0, y: -10.0, z: 700.066),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z203",
                position: .init(x: 315.0, y: -6.5001454, z: 700.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z204z27p",
                position: .init(x: -220.0, y: -10.0, z: 480.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z205",
                position: .init(x: -220.0, y: -6.500097, z: 475.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z206z27r",
                position: .init(x: -520.0, y: -10.0, z: 740.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z207",
                position: .init(x: -515.0, y: -6.5001, z: 740.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z208z27t",
                position: .init(x: -240.0, y: -10.0, z: 220.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z209",
                position: .init(x: -235.0, y: -6.500097, z: 220.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z20az1gh",
                position: .init(x: 320.0, y: -10.435975, z: -620.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z20b",
                position: .init(x: 325.0, y: -6.574339, z: -620.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z20cz1gj",
                position: .init(x: -120.0, y: -10.0, z: -620.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z20d",
                position: .init(x: -115.0, y: -6.5001454, z: -620.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z20ez1pn",
                position: .init(x: 100.014015, y: -10.0, z: -680.0199),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z20f",
                position: .init(x: 100.0, y: -6.500097, z: -675.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 5.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}