//
//  MohGates.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct MohGates: ZoneSceneMetadata {
        public let id = Zone.mohGates.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z2p2z2o5",
                position: .init(x: -614.87885, y: -14.53825, z: -419.43466),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 15.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z2p3",
                position: .init(x: -614.04095, y: -14.181, z: -416.25952),
                rotation: .init(x: 0.0, y: 5.061455, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 3.0)
            ),
            .init(
                name: "z2p8z2q1",
                position: .init(x: -454.59283, y: 23.968311, z: 661.7626),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 20.0, y: 15.0, z: 3.0)
            ),
            .init(
                name: "z2p9",
                position: .init(x: -454.13455, y: 28.409458, z: 657.79),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z2paz2r1",
                position: .init(x: 756.2681, y: -35.64283, z: -40.03968),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 20.0, y: 10.0, z: 3.0)
            ),
            .init(
                name: "z2pb",
                position: .init(x: 730.0, y: -33.662502, z: -40.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z2p0z2o3",
                position: .init(x: 540.0, y: -20.9089, z: -602.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 12.0, y: 10.0, z: 3.0)
            ),
            .init(
                name: "z2p1",
                position: .init(x: 540.0, y: -19.354519, z: -599.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z2p4z2o7",
                position: .init(x: -654.6383, y: -22.263994, z: 60.57983),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 15.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z2p5",
                position: .init(x: -654.0597, y: -20.129862, z: 63.53578),
                rotation: .init(x: 0.0, y: 5.061455, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 3.0)
            ),
            .init(
                name: "z2p6z2o9",
                position: .init(x: -653.4563, y: -14.4785, z: 217.24992),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 15.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z2p7",
                position: .init(x: -652.23944, y: -12.3047, z: 213.95074),
                rotation: .init(x: 0.0, y: 1.134464, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}