//
//  MonarchLinn.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct MonarchLinn: ZoneSceneMetadata {
        public let id = Zone.monarchLinn.rawValue
        public let name = "Monarch Linn"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}