//
//  MordionGaol.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct MordionGaol: ZoneSceneMetadata {
    public let id = Zone.mordionGaol.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z0k0z0l1",
            position: .init(x: 100.0, y: -2.2949896, z: 180.03525),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 8.0)
        ),
        .init(
            name: "z0k1",
            position: .init(x: 100.0, y: -2.0592487, z: 183.06801),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 6.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}