//
//  Nashmau.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct Nashmau: ZoneSceneMetadata {
        public let id = Zone.nashmau.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z4f1",
                position: .init(x: 179.98561, y: -9.693797, z: 41.970715),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4f0z3gd",
                position: .init(x: 179.98593, y: -10.897386, z: 44.57529),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4f3",
                position: .init(x: 59.995796, y: -9.598468, z: 81.9875),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4f2z3gf",
                position: .init(x: 60.014736, y: -10.929499, z: 84.513435),
                rotation: .init(x: 0.0, y: 1.566118, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4f5",
                position: .init(x: -59.955887, y: -9.725262, z: 81.95733),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4f4z3gh",
                position: .init(x: -59.978313, y: -11.205737, z: 84.54707),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4f7",
                position: .init(x: 198.94246, y: -17.706015, z: 300.01984),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4f6z3gl",
                position: .init(x: 195.93741, y: -19.21502, z: 300.01407),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4f9",
                position: .init(x: 238.95056, y: -9.729553, z: 179.99834),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4f8z3gj",
                position: .init(x: 235.93329, y: -11.406682, z: 179.98793),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4fb",
                position: .init(x: 432.0134, y: 5.3526855, z: 216.47171),
                rotation: .init(x: 0.0, y: 4.87613, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4faz4g1",
                position: .init(x: 430.46475, y: 5.2679033, z: 213.31207),
                rotation: .init(x: 0.0, y: 5.1100497, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4fd",
                position: .init(x: 8.339575, y: 5.038993, z: 15.883975),
                rotation: .init(x: 0.0, y: 4.5392923, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4fcz4g3",
                position: .init(x: 9.383601, y: 5.0851665, z: 13.076929),
                rotation: .init(x: 0.0, y: 4.37087, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4ff",
                position: .init(x: -231.60153, y: 5.048991, z: -103.51549),
                rotation: .init(x: 0.0, y: 4.511223, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4fez4g5",
                position: .init(x: -230.89702, y: 5.02576, z: -106.53468),
                rotation: .init(x: 0.0, y: 4.4562073, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4fh",
                position: .init(x: -16.736814, y: 5.219859, z: 31.904873),
                rotation: .init(x: 0.0, y: 3.4456837, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4fgz4g7",
                position: .init(x: -13.745236, y: 5.1805654, z: 30.687681),
                rotation: .init(x: 0.0, y: 3.3801868, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z4fj",
                position: .init(x: -231.70134, y: 3.272511, z: 64.6054),
                rotation: .init(x: 0.0, y: 1.8643218, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4fiz4j1",
                position: .init(x: -230.36438, y: 3.011286, z: 67.21091),
                rotation: .init(x: 0.0, y: 1.9967816, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}