//
//  NavukgoExecutionChamber.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct NavukgoExecutionChamber: ZoneSceneMetadata {
    public let id = Zone.navukgoExecutionChamber.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z3c0z3b3",
            position: .init(x: 519.8873, y: -21.817097, z: -507.8994),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 30.0, y: 20.0, z: 3.0)
        ),
        .init(
            name: "z3c1",
            position: .init(x: 520.391, y: -15.884677, z: -502.917),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
        .init(
            name: "z3c2z325",
            position: .init(x: -480.019, y: -9.17535, z: 200.836),
            rotation: .init(x: 0.0, y: 1.2217305, z: 0.0),
            scale: .init(x: 40.0, y: 20.0, z: 3.0)
        ),
        .init(
            name: "z3c3",
            position: .init(x: -475.679, y: -3.2284591, z: 201.675),
            rotation: .init(x: 0.0, y: 5.934119, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 10.0)
        ),
        .init(
            name: "z3c4z6u1",
            position: .init(x: -579.98474, y: -3.8813744, z: 399.83914),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 30.0, y: 20.0, z: 3.0)
        ),
        .init(
            name: "z3c5",
            position: .init(x: -574.6468, y: -0.6800225, z: 399.97427),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
        .init(
            name: "z3c6z5k1",
            position: .init(x: -104.00145, y: -27.307228, z: -427.82565),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 8.0, y: 6.0, z: 2.0)
        ),
        .init(
            name: "z3c7",
            position: .init(x: -103.99114, y: -25.956337, z: -425.22076),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 2.0, z: 3.0)
        ),
        .init(
            name: "z3c8z5k3",
            position: .init(x: 263.99127, y: -3.402346, z: -390.0485),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 8.0, y: 6.0, z: 2.0)
        ),
        .init(
            name: "z3c9",
            position: .init(x: 264.0016, y: -1.7476444, z: -387.4436),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 2.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}