//
//  NewtonMovalpolos.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct NewtonMovalpolos: ZoneSceneMetadata {
        public let id = Zone.newtonMovalpolos.rawValue
        public let name = "Newton Movalpolos"
        public let lines: [ZoneLine] = [
            .init(
                name: "z2h0z2g3",
                position: .init(x: -680.0, y: 41.9295, z: -880.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 25.0)
            ),
            .init(
                name: "z2h1",
                position: .init(x: -675.0, y: 41.208706, z: -880.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z2h2z2i1",
                position: .init(x: 489.49, y: 71.69533, z: 927.574),
                rotation: .init(x: 0.0, y: 0.6981317, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 50.0)
            ),
            .init(
                name: "z2h3",
                position: .init(x: 495.0631, y: 69.90314, z: 924.1015),
                rotation: .init(x: 0.0, y: 0.6981317, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z2h4z2i3",
                position: .init(x: 759.2085, y: 65.9402, z: 834.3762),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 40.0)
            ),
            .init(
                name: "z2h5",
                position: .init(x: 759.68414, y: 66.25037, z: 829.35645),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}