//
//  NorthGustaberg.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct NorthGustaberg: ZoneSceneMetadata {
        public let id = Zone.northGustaberg.rawValue
        public let name = "North Gustaberg"
        public let lines: [ZoneLine] = [
            .init(
                name: "z7f0z7l9",
                position: .init(x: 500.5, y: 68.500465, z: -483.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 12.0)
            ),
            .init(
                name: "z7f1",
                position: .init(x: 500.5, y: 70.922, z: -479.5),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
            .init(
                name: "z7f3",
                position: .init(x: -319.5, y: 40.90741, z: -459.5),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
            .init(
                name: "z7f2z7t1",
                position: .init(x: -323.0, y: 37.76649, z: -460.5),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 12.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}