//
//  OrdelleSCaves.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct OrdelleSCaves: ZoneSceneMetadata {
    public let id = Zone.ordelleSCaves.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z0c0z0b7",
            position: .init(x: -264.7916, y: 9.903098, z: 180.3916),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z0c1",
            position: .init(x: -261.85794, y: 10.857847, z: 180.55919),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z0c2z0b9",
            position: .init(x: -219.79013, y: 8.774826, z: 40.947235),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z0c3",
            position: .init(x: -220.03075, y: 10.064901, z: 43.605003),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z0c4z0bb",
            position: .init(x: -144.60397, y: 9.139311, z: -19.511057),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z0c5",
            position: .init(x: -141.8826, y: 10.737331, z: -19.373362),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z0c6z0bd",
            position: .init(x: -198.92339, y: 4.7985115, z: -60.045593),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z0c7",
            position: .init(x: -196.06587, y: 6.087678, z: -59.949192),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z0c8z0bf",
            position: .init(x: -259.93417, y: 9.171012, z: -120.90676),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z0c9",
            position: .init(x: -260.00436, y: 10.147523, z: -123.784706),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z0caz0bh",
            position: .init(x: -359.77066, y: 4.9635487, z: -179.99919),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z0cb",
            position: .init(x: -356.9445, y: 6.0465436, z: -179.97415),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z0ccz0d1",
            position: .init(x: 454.9123, y: 25.13244, z: -19.355278),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z0cd",
            position: .init(x: 451.8946, y: 26.214258, z: -19.782305),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z0cez0d3",
            position: .init(x: 218.12582, y: 17.189028, z: 187.42767),
            rotation: .init(x: 0.0, y: 2.1816616, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z0cf",
            position: .init(x: 215.99135, y: 18.07058, z: 185.11256),
            rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}