//
//  OrdelleSCaves.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct OrdelleSCaves: ZoneSceneMetadata {
        public let id = Zone.ordelleSCaves.rawValue
        public let name = "Ordelle's Caves"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}