//
//  OuterRaKaznarU.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct OuterRaKaznarU: ZoneSceneMetadata {
        public let id = Zone.outerRaKaznarU.rawValue
        public let name = "Outer Ra'Kaznar [U]"
        public let lines: [ZoneLine] = [
            .init(
                name: "z361",
                position: .init(x: 499.83932, y: 5.391097, z: -76.8092),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z360z4t3",
                position: .init(x: 499.9788, y: 4.509023, z: -79.97247),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z365",
                position: .init(x: -320.01636, y: 25.995007, z: -100.021),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z364z3h7",
                position: .init(x: -325.06647, y: 25.1625, z: -99.66215),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z367",
                position: .init(x: 420.00223, y: 8.362197, z: 191.73935),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z366z5s1",
                position: .init(x: 420.0633, y: 6.397522, z: 194.87442),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z363",
                position: .init(x: 260.08957, y: 6.012701, z: 320.4542),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z362z3h1",
                position: .init(x: 260.28214, y: 5.015691, z: 323.97543),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z369",
                position: .init(x: 19.98019, y: 16.528734, z: -321.52637),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z368z5s3",
                position: .init(x: 20.04945, y: 14.297431, z: -325.0035),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z36b",
                position: .init(x: 126.59714, y: 8.245438, z: -20.011692),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z36az5s9",
                position: .init(x: 129.98004, y: 6.1919394, z: -20.013987),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z36d",
                position: .init(x: 80.8661, y: 8.463577, z: -100.362175),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z36cz5t3",
                position: .init(x: 85.051765, y: 6.503766, z: -99.86685),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}