//
//  OuterRaKaznar.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct OuterRaKaznar: ZoneSceneMetadata {
        public let id = Zone.outerRaKaznar.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z2q0z2p9",
                position: .init(x: 519.8873, y: -21.817097, z: -507.8994),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 30.0, y: 20.0, z: 3.0)
            ),
            .init(
                name: "z2q1",
                position: .init(x: 520.391, y: -15.884677, z: -502.917),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 6.0)
            ),
            .init(
                name: "z2q2z2j5",
                position: .init(x: -458.5577, y: -6.959915, z: 205.42354),
                rotation: .init(x: 0.0, y: 1.0471976, z: 0.0),
                scale: .init(x: 40.0, y: 20.0, z: 3.0)
            ),
            .init(
                name: "z2q3",
                position: .init(x: -454.2177, y: -2.9233627, z: 206.26253),
                rotation: .init(x: 0.0, y: 5.7595863, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 10.0)
            ),
            .init(
                name: "z2q4z4k1",
                position: .init(x: -104.00145, y: -27.307228, z: -427.82565),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 8.0, y: 6.0, z: 2.0)
            ),
            .init(
                name: "z2q5",
                position: .init(x: -104.0, y: -25.359966, z: -410.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 2.0, z: 3.0)
            ),
            .init(
                name: "z2q6z4k3",
                position: .init(x: 263.99127, y: -3.402346, z: -390.0485),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 8.0, y: 6.0, z: 2.0)
            ),
            .init(
                name: "z2q7",
                position: .init(x: 264.0, y: -1.3599663, z: -370.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 2.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}