//
//  OuterRaKaznar.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct OuterRaKaznar: ZoneSceneMetadata {
        public let id = Zone.outerRaKaznar.rawValue
        public let name = "Outer Ra'Kaznar"
        public let lines: [ZoneLine] = [
            .init(
                name: "z370z6m1",
                position: .init(x: 320.00952, y: -8.221529, z: -48.071106),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 10.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z371",
                position: .init(x: 320.0181, y: -6.6841784, z: -45.165775),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z372z6o1",
                position: .init(x: 169.19696, y: -3.7508152, z: -320.032),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 10.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z373",
                position: .init(x: 166.61247, y: -2.610087, z: -319.97162),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z374z383",
                position: .init(x: 504.43594, y: -13.688822, z: 133.854),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 12.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z375",
                position: .init(x: 501.20853, y: -12.111086, z: 134.43173),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
            .init(
                name: "z376z385",
                position: .init(x: 425.197, y: -29.483103, z: 693.49054),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 12.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z377",
                position: .init(x: 421.96957, y: -28.058903, z: 694.0683),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
            .init(
                name: "z378z411",
                position: .init(x: -374.54584, y: -25.351173, z: 61.09062),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 12.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z379",
                position: .init(x: -374.00754, y: -23.71199, z: 63.288757),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 3.0)
            ),
            .init(
                name: "z37cz5e9",
                position: .init(x: -340.006, y: 8.096825, z: -399.521),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 12.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z37d",
                position: .init(x: -339.959, y: 8.354569, z: -396.924),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z37ez5cb",
                position: .init(x: 221.24484, y: -0.63427985, z: 39.305946),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 12.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z37f",
                position: .init(x: 223.7064, y: 0.1142015, z: 39.97595),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z37az5e1",
                position: .init(x: -279.15964, y: -12.112257, z: 660.0504),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 12.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z37b",
                position: .init(x: -276.4095, y: -11.665107, z: 660.009),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z37gz423",
                position: .init(x: -228.61252, y: -10.4023695, z: -186.11111),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 8.0, y: 8.0, z: 2.0)
            ),
            .init(
                name: "z37h",
                position: .init(x: -225.9207, y: -8.401308, z: -185.2842),
                rotation: .init(x: 0.0, y: 5.8590074, z: 0.0),
                scale: .init(x: 1.0, y: 2.0, z: 2.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}