//
//  OuterHorutotoRuins.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct OuterHorutotoRuins: ZoneSceneMetadata {
    public let id = Zone.outerHorutotoRuins.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z330z4m3",
            position: .init(x: -542.0441, y: -44.593422, z: -378.67374),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z331",
            position: .init(x: -538.23334, y: -42.188786, z: -377.3905),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z332z341",
            position: .init(x: -251.9569, y: -86.89305, z: 260.65454),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 16.0, z: 15.0)
        ),
        .init(
            name: "z333",
            position: .init(x: -247.91113, y: -82.16454, z: 260.20654),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z334z2x7",
            position: .init(x: 18.084078, y: -4.2975936, z: -658.11993),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 14.0)
        ),
        .init(
            name: "z335",
            position: .init(x: 17.331057, y: -2.812844, z: -654.23016),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z336z5o1",
            position: .init(x: 280.02, y: 15.917044, z: 571.937),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 18.0)
        ),
        .init(
            name: "z337",
            position: .init(x: 280.02512, y: 17.88094, z: 568.5866),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z338z091",
            position: .init(x: 238.82571, y: 5.2072, z: -20.012478),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 15.0)
        ),
        .init(
            name: "z339",
            position: .init(x: 242.29166, y: 4.949996, z: -20.005484),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z33az093",
            position: .init(x: 60.001976, y: 5.5677633, z: -361.11783),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 15.0)
        ),
        .init(
            name: "z33b",
            position: .init(x: 60.008465, y: 4.949996, z: -357.67926),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z33cz095",
            position: .init(x: 100.00499, y: -14.567866, z: 161.19853),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 15.0)
        ),
        .init(
            name: "z33d",
            position: .init(x: 100.01115, y: -15.050004, z: 157.69452),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z33ez097",
            position: .init(x: -201.16301, y: -34.9234, z: -219.98244),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 15.0)
        ),
        .init(
            name: "z33f",
            position: .init(x: -197.71701, y: -35.050003, z: -219.99521),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z33gz099",
            position: .init(x: -19.974636, y: -55.084743, z: -38.825283),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 15.0)
        ),
        .init(
            name: "z33h",
            position: .init(x: -19.995775, y: -55.050003, z: -42.291237),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z33iz09b",
            position: .init(x: -339.95236, y: -95.08197, z: 161.19757),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 15.0)
        ),
        .init(
            name: "z33j",
            position: .init(x: -339.9735, y: -95.05001, z: 157.73161),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}