//
//  OuterHorutotoRuins.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct OuterHorutotoRuins: ZoneSceneMetadata {
        public let id = Zone.outerHorutotoRuins.rawValue
        public let name = "Outer Horutoto Ruins"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}