//
//  PashhowMarshlandsS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct PashhowMarshlandsS: ZoneSceneMetadata {
        public let id = Zone.pashhowMarshlandsS.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z7e1",
                position: .init(x: 440.0, y: -62.5995, z: 300.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 4.0)
            ),
            .init(
                name: "z7e0z7k5",
                position: .init(x: 445.0, y: -64.30263, z: 299.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z7e3",
                position: .init(x: -500.0, y: -42.53, z: 320.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 4.0)
            ),
            .init(
                name: "z7e2z7l5",
                position: .init(x: -501.0, y: -42.53, z: 325.0),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}