//
//  Periqia.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct Periqia: ZoneSceneMetadata {
        public let id = Zone.periqia.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z5r0z5p5",
                position: .init(x: -698.59485, y: -3.593978, z: -650.2002),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 13.0)
            ),
            .init(
                name: "z5r1",
                position: .init(x: -698.7286, y: -1.0454957, z: -646.65875),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}