//
//  PhomiunaAqueducts.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct PhomiunaAqueducts: ZoneSceneMetadata {
        public let id = Zone.phomiunaAqueducts.rawValue
        public let name = "Phomiuna Aqueducts"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}