//
//  PromyvionHolla.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct PromyvionHolla: ZoneSceneMetadata {
        public let id = Zone.promyvionHolla.rawValue
        public let name = "Promyvion - Holla"
        public let lines: [ZoneLine] = [
            .init(
                name: "z2d1",
                position: .init(x: 236.5, y: -2.250004, z: 20.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2d0z2ab",
                position: .init(x: 240.0, y: -4.47001, z: 20.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 18.0, y: 10.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}