//
//  PromyvionVahzl.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct PromyvionVahzl: ZoneSceneMetadata {
        public let id = Zone.promyvionVahzl.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z5t0z5sr",
                position: .init(x: -580.92365, y: -2.0695643, z: -567.9507),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z5t1",
                position: .init(x: -580.383, y: -0.8203251, z: -563.95605),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5t2z36d",
                position: .init(x: -640.0092, y: -18.379833, z: -499.99945),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 14.0)
            ),
            .init(
                name: "z5t3",
                position: .init(x: -636.0011, y: -16.562717, z: -500.02316),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}