//
//  PsoXja.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct PsoXja: ZoneSceneMetadata {
    public let id = Zone.psoXja.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z5q0z5o3",
            position: .init(x: -243.97865, y: -27.155508, z: 19.997913),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 10.0)
        ),
        .init(
            name: "z5q1",
            position: .init(x: -241.04617, y: -25.86, z: 19.990995),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z5q2z5o5",
            position: .init(x: -65.02739, y: -31.19019, z: -80.01995),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 10.0)
        ),
        .init(
            name: "z5q3",
            position: .init(x: -62.094906, y: -30.074018, z: -80.02687),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}