//
//  QuBiaArena.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct QuBiaArena: ZoneSceneMetadata {
    public let id = Zone.quBiaArena.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z6n0z6m5",
            position: .init(x: -204.979, y: -7.03141, z: 139.551),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "zmr8zmr9",
            position: .init(x: -259.84924, y: -8.494113, z: -120.050995),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z6n2z6p5",
            position: .init(x: 100.505, y: -7.090411, z: -166.49),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z6n1",
            position: .init(x: -193.62749, y: -5.5853653, z: 140.50497),
            rotation: .init(x: 0.0, y: 5.9341197, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z6n3",
            position: .init(x: 99.7718, y: -5.6241946, z: -154.266),
            rotation: .init(x: 0.0, y: 4.363323, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "zmr9",
            position: .init(x: -256.7803, y: -7.6276603, z: -119.97335),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z6n6z4p3",
            position: .init(x: -18.340084, y: -2.7091339, z: 253.68008),
            rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z6n7",
            position: .init(x: -16.435627, y: -1.9404709, z: 255.54596),
            rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}