//
//  QufimIsland.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct QufimIsland: ZoneSceneMetadata {
    public let id = Zone.qufimIsland.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z1fkz1c1",
            position: .init(x: 614.376, y: -27.1435, z: 356.287),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 15.0, z: 28.0)
        ),
        .init(
            name: "z1fmz1g1",
            position: .init(x: 381.29306, y: -15.564766, z: 440.7946),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 15.0, z: 20.0)
        ),
        .init(
            name: "z1f8z1w9",
            position: .init(x: 60.0172, y: -14.5681, z: 399.995),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1faz1wb",
            position: .init(x: -259.43362, y: -18.95274, z: 306.4979),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1foz1q1",
            position: .init(x: -853.48773, y: -19.409376, z: 99.99019),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1fcz1wd",
            position: .init(x: -679.9702, y: -7.950361, z: -20.006996),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1fez1wf",
            position: .init(x: -420.0181, y: -7.38928, z: -80.01478),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1f0z1w1",
            position: .init(x: 440.03198, y: -22.7211, z: -100.039),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1f2z1w3",
            position: .init(x: 99.42827, y: -11.3129, z: -146.551),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1f4z1w5",
            position: .init(x: -173.52861, y: -11.7185, z: -260.572),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1fgz1wh",
            position: .init(x: -333.49097, y: -19.647253, z: -180.88654),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1f6z1w7",
            position: .init(x: -334.40326, y: -11.860147, z: -379.995),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1fuz1t5",
            position: .init(x: -570.5201, y: -20.788939, z: -781.0547),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z1fqz1t1",
            position: .init(x: -480.45538, y: -7.9823976, z: -539.9903),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z1fsz1t3",
            position: .init(x: -739.0636, y: -5.158458, z: -569.55286),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z1fiz1wj",
            position: .init(x: -550.506, y: -13.216402, z: -221.456),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 10.0, z: 15.0)
        ),
        .init(
            name: "z1f1",
            position: .init(x: 444.495, y: -22.119621, z: -99.9764),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1f3",
            position: .init(x: 99.04914, y: -12.592459, z: -150.95372),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1f5",
            position: .init(x: -168.52904, y: -12.902374, z: -260.8032),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1f7",
            position: .init(x: -328.49503, y: -12.892765, z: -379.39746),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1f9",
            position: .init(x: 59.975784, y: -13.674497, z: 404.46997),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1fb",
            position: .init(x: -258.9989, y: -20.903347, z: 311.538),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1fd",
            position: .init(x: -675.4972, y: -5.779958, z: -19.657494),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1ff",
            position: .init(x: -419.2925, y: -5.752643, z: -84.47489),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1fh",
            position: .init(x: -328.53445, y: -20.85156, z: -180.81885),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1fj",
            position: .init(x: -555.51697, y: -13.729722, z: -220.20082),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1fl",
            position: .init(x: 610.542, y: -28.546867, z: 356.247),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 6.0, z: 15.0)
        ),
        .init(
            name: "z1fn",
            position: .init(x: 380.03055, y: -13.369688, z: 435.50967),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 6.0)
        ),
        .init(
            name: "z1fp",
            position: .init(x: -848.50336, y: -20.834614, z: 100.58251),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1fr",
            position: .init(x: -475.4517, y: -5.9245067, z: -539.9601),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1ft",
            position: .init(x: -739.5488, y: -5.501932, z: -565.1459),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
        .init(
            name: "z1fv",
            position: .init(x: -565.5167, y: -21.502514, z: -780.59607),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.5, z: 3.5)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}