//
//  QuicksandCaves.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct QuicksandCaves: ZoneSceneMetadata {
    public let id = Zone.quicksandCaves.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z4s1",
            position: .init(x: 20.51047, y: -1.5832851, z: 4.018677),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z4s0z6i5",
            position: .init(x: 23.038723, y: -2.6220057, z: 3.8510468),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 6.0, z: 10.0)
        ),
        .init(
            name: "z4s3",
            position: .init(x: -270.7074, y: 14.159488, z: -20.26814),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4s2z4t1",
            position: .init(x: -273.927, y: 12.872459, z: -20.2559),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}