//
//  QulunDome.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct QulunDome: ZoneSceneMetadata {
        public let id = Zone.qulunDome.rawValue
        public let name = "Qulun Dome"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}