//
//  Rabao.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct Rabao: ZoneSceneMetadata {
        public let id = Zone.rabao.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z2y0z6k1",
                position: .init(x: 660.0462, y: -3.0851355, z: 302.72546),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 10.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z2y1",
                position: .init(x: 660.0039, y: -2.4777646, z: 306.23648),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 5.0)
            ),
            .init(
                name: "z2y2z2z5",
                position: .init(x: 0.73537284, y: -5.5548854, z: -79.06469),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 25.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z2y3",
                position: .init(x: 0.019840762, y: -4.4094315, z: -75.40513),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 8.0)
            ),
            .init(
                name: "z2y4z2z7",
                position: .init(x: -440.63852, y: 33.09447, z: -276.30817),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 25.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z2y5",
                position: .init(x: -440.79156, y: 35.531025, z: -272.90128),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 8.0)
            ),
            .init(
                name: "z2y6z301",
                position: .init(x: -518.8285, y: 33.03432, z: 592.07446),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 25.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z2y7",
                position: .init(x: -518.86707, y: 35.53782, z: 588.6397),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 8.0)
            ),
            .init(
                name: "z2y8z3z1",
                position: .init(x: 497.89926, y: -37.5166, z: 1174.924),
                rotation: .init(x: 0.0, y: 1.0471975, z: 0.0),
                scale: .init(x: 10.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z2y9",
                position: .init(x: 495.99878, y: -36.646736, z: 1172.9099),
                rotation: .init(x: 0.0, y: 2.443461, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2yaz5b3",
                position: .init(x: -697.0123, y: 92.17469, z: 311.8292),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 12.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z2yb",
                position: .init(x: -694.5421, y: 93.09737, z: 314.1676),
                rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z2ycz0b1",
                position: .init(x: 580.98627, y: -17.809452, z: 695.89923),
                rotation: .init(x: 0.0, y: 1.2217305, z: 0.0),
                scale: .init(x: 10.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z2yd",
                position: .init(x: 575.5894, y: -16.6774, z: 692.8638),
                rotation: .init(x: 0.0, y: 2.443461, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2yez0b3",
                position: .init(x: 461.25546, y: -8.138728, z: 736.0629),
                rotation: .init(x: 0.0, y: 1.2217305, z: 0.0),
                scale: .init(x: 10.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z2yf",
                position: .init(x: 455.8586, y: -6.690063, z: 733.02747),
                rotation: .init(x: 0.0, y: 2.443461, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}