//
//  RaKaznarTurris.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct RaKaznarTurris: ZoneSceneMetadata {
        public let id = Zone.raKaznarTurris.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z0g0z0h1",
                position: .init(x: 180.0, y: -2.17448, z: -19.99201),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 8.0)
            ),
            .init(
                name: "z0g1",
                position: .init(x: 179.97333, y: -2.10038, z: -23.145319),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}