//
//  RalaWaterwaysU.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct RalaWaterwaysU: ZoneSceneMetadata {
        public let id = Zone.ralaWaterwaysU.rawValue
        public let name = "Rala Waterways [U]"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}