//
//  RanguemontPass.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct RanguemontPass: ZoneSceneMetadata {
        public let id = Zone.ranguemontPass.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z2x0z2w3",
                position: .init(x: -444.042, y: -16.1663, z: -240.077),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 35.0)
            ),
            .init(
                name: "z2x1",
                position: .init(x: -439.3931, y: -11.764935, z: -239.95845),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 10.0)
            ),
            .init(
                name: "z2x2z323",
                position: .init(x: 479.95493, y: -0.7864058, z: -363.91336),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 50.0)
            ),
            .init(
                name: "z2x3",
                position: .init(x: 479.744, y: 3.3375435, z: -359.84),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 15.0)
            ),
            .init(
                name: "z2x6z335",
                position: .init(x: -501.56024, y: -40.54111, z: 508.76788),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2x7",
                position: .init(x: -500.45078, y: -39.710236, z: 504.89413),
                rotation: .init(x: 0.0, y: 1.1192538, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2x8z5f3",
                position: .init(x: -467.2726, y: -23.039799, z: 332.7245),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2x9",
                position: .init(x: -464.85284, y: -22.563198, z: 335.13574),
                rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2xaz5f5",
                position: .init(x: -212.7248, y: -7.42377, z: 132.69537),
                rotation: .init(x: 0.0, y: 3.926991, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2xb",
                position: .init(x: -214.55034, y: -6.5420375, z: 134.5545),
                rotation: .init(x: 0.0, y: 3.926991, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2xcz5f7",
                position: .init(x: 52.69474, y: 0.3476985, z: 132.70148),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2xd",
                position: .init(x: 54.593536, y: 0.9777633, z: 134.59418),
                rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2xez5f9",
                position: .init(x: -135.32129, y: -7.4353256, z: -15.5262),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2xf",
                position: .init(x: -133.60371, y: -6.6240196, z: -13.813568),
                rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2xgz5fb",
                position: .init(x: -224.54454, y: -23.550278, z: -64.536575),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2xh",
                position: .init(x: -226.39279, y: -22.627724, z: -66.37785),
                rotation: .init(x: 0.0, y: 2.356194, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2xiz5fd",
                position: .init(x: 132.64809, y: 8.566454, z: -372.6632),
                rotation: .init(x: 0.0, y: 3.926991, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2xj",
                position: .init(x: 134.40216, y: 9.438424, z: -374.4047),
                rotation: .init(x: 0.0, y: 0.7853975, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2xkz5ff",
                position: .init(x: 162.94978, y: 21.998287, z: -605.29675),
                rotation: .init(x: 0.0, y: 2.5904849, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2xl",
                position: .init(x: 165.52086, y: 22.217731, z: -603.0058),
                rotation: .init(x: 0.0, y: 5.174027, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z2xmz5f1",
                position: .init(x: -695.36273, y: -15.756116, z: 175.33167),
                rotation: .init(x: 0.0, y: 3.926991, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2xn",
                position: .init(x: -693.60864, y: -14.582591, z: 173.59018),
                rotation: .init(x: 0.0, y: 0.7853975, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z2x4z6s1",
                position: .init(x: 491.91776, y: 1.1713591, z: -159.98181),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 50.0)
            ),
            .init(
                name: "z2x5",
                position: .init(x: 486.2985, y: 4.1689587, z: -159.95287),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 6.0, z: 10.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}