//
//  ResidentialArea3.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct ResidentialArea3: ZoneSceneMetadata {
    public let id = Zone.residentialArea3.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z380z6p1",
            position: .init(x: -128.0699, y: -7.9030414, z: -520.01385),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z381",
            position: .init(x: -125.63818, y: -6.6016235, z: -520.0004),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 5.0)
        ),
        .init(
            name: "z382z375",
            position: .init(x: -343.926, y: -13.6958, z: 106.455),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z383",
            position: .init(x: -341.494, y: -12.089386, z: 106.469),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 3.0)
        ),
        .init(
            name: "z384z377",
            position: .init(x: -425.512, y: -30.6921, z: 600.89026),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 20.0)
        ),
        .init(
            name: "z385",
            position: .init(x: -422.94022, y: -28.93533, z: 601.4634),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 8.0)
        ),
        .init(
            name: "z386z391",
            position: .init(x: 306.10052, y: -37.75342, z: 664.73334),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z387",
            position: .init(x: 305.37708, y: -36.09193, z: 660.4348),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 3.0)
        ),
        .init(
            name: "z38cz5e7",
            position: .init(x: 259.99628, y: -12.116645, z: -479.06024),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z38d",
            position: .init(x: 259.99927, y: -11.6606245, z: -476.2113),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z38az5c5",
            position: .init(x: 399.29395, y: -8.286653, z: 99.967606),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z38b",
            position: .init(x: 396.22537, y: -7.669358, z: 99.98923),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z388z5e3",
            position: .init(x: -60.01978, y: -32.34418, z: 759.39703),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z389",
            position: .init(x: -59.996178, y: -31.676891, z: 756.2489),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}