//
//  ResidentialArea2.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct ResidentialArea2: ZoneSceneMetadata {
        public let id = Zone.residentialArea2.rawValue
        public let name = "Residential_Area2"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}