//
//  RiverneSiteB01.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct RiverneSiteB01: ZoneSceneMetadata {
        public let id = Zone.riverneSiteB01.rawValue
        public let name = "Riverne - Site #B01"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}