//
//  RiverneSiteA01.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct RiverneSiteA01: ZoneSceneMetadata {
    public let id = Zone.riverneSiteA01.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z5l1",
            position: .init(x: -399.541, y: -1.6969447, z: -420.0),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z5l0z359",
            position: .init(x: -403.02808, y: -3.7935586, z: -420.0012),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 13.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}