//
//  RolanberryFields.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct RolanberryFields: ZoneSceneMetadata {
        public let id = Zone.rolanberryFields.rawValue
        public let name = "Rolanberry Fields"
        public let lines: [ZoneLine] = [
            .init(
                name: "z7b0z7i9",
                position: .init(x: 235.0, y: 3.83, z: 59.5),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z7b1",
                position: .init(x: 240.0, y: 6.15, z: 59.5),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z7b2z7l3",
                position: .init(x: -405.0, y: 4.1152816, z: 259.5),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z7b3",
                position: .init(x: -400.0, y: 6.1, z: 260.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}