//
//  RoMaeve.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct RoMaeve: ZoneSceneMetadata {
    public let id = Zone.roMaeve.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z5n0z5o7",
            position: .init(x: 500.039, y: -4.6217475, z: 519.998),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z5n1",
            position: .init(x: 499.9927, y: -1.696363, z: 523.3427),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z5n2z5o9",
            position: .init(x: -453.01917, y: -23.03711, z: -399.99512),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z5n3",
            position: .init(x: -449.49957, y: -21.93568, z: -399.97583),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}