//
//  RuAunGardens.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct RuAunGardens: ZoneSceneMetadata {
        public let id = Zone.ruAunGardens.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z7g1",
                position: .init(x: -41.0, y: -31.6019, z: -20.1658),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z7g0z799",
                position: .init(x: -36.5, y: -33.662357, z: -19.748),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 13.0)
            ),
            .init(
                name: "z7g3",
                position: .init(x: -260.0, y: -31.549992, z: 39.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z7g2z797",
                position: .init(x: -260.0, y: -33.513054, z: 43.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 13.0)
            ),
            .init(
                name: "z7g9",
                position: .init(x: -500.38773, y: -41.804573, z: -0.26086098),
                rotation: .init(x: 0.0, y: 1.3089969, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z7g8z7i7",
                position: .init(x: -501.283, y: -44.428852, z: 4.1970162),
                rotation: .init(x: 0.0, y: 1.3089969, z: 0.0),
                scale: .init(x: 2.0, y: 9.0, z: 14.0)
            ),
            .init(
                name: "z7g5",
                position: .init(x: -159.5, y: -31.56934, z: -420.2677),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z7g4z7a1",
                position: .init(x: -164.07762, y: -34.005085, z: -420.7724),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 13.0)
            ),
            .init(
                name: "z7g7",
                position: .init(x: -299.84863, y: -21.5878, z: -438.15396),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z7g6z7a3",
                position: .init(x: -299.669, y: -23.89102, z: -443.428),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 13.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}