//
//  RuhotzSilvermines.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct RuhotzSilvermines: ZoneSceneMetadata {
        public let id = Zone.ruhotzSilvermines.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z5m0z497",
                position: .init(x: 514.0613, y: -19.553415, z: 539.2581),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 12.0)
            ),
            .init(
                name: "z5m1",
                position: .init(x: 517.95654, y: -18.01334, z: 540.0449),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z5m2z499",
                position: .init(x: -527.02167, y: 5.411641, z: -500.80606),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 12.0)
            ),
            .init(
                name: "z5m3",
                position: .init(x: -523.1264, y: 6.808345, z: -500.01926),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}