//
//  RuLudeGardens.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct RuLudeGardens: ZoneSceneMetadata {
        public let id = Zone.ruLudeGardens.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z6t0z327",
                position: .init(x: -123.064705, y: -4.434821, z: -200.69084),
                rotation: .init(x: 0.0, y: 2.0943952, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z6t1",
                position: .init(x: -121.658615, y: -2.0532103, z: -198.24686),
                rotation: .init(x: 0.0, y: 5.235987, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "zmruzmrr",
                position: .init(x: 43.943928, y: -9.359029, z: 88.58044),
                rotation: .init(x: 0.0, y: 2.0943952, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "zmrr",
                position: .init(x: 42.500008, y: -6.733176, z: 86.07368),
                rotation: .init(x: 0.0, y: 2.0944552, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z6t4z6u3",
                position: .init(x: 29.693565, y: -3.0192096, z: 41.44375),
                rotation: .init(x: 0.0, y: 3.6279035, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z6t5",
                position: .init(x: 27.891224, y: -2.6348512, z: 42.422886),
                rotation: .init(x: 0.0, y: 3.6530406, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z6t2z6s3",
                position: .init(x: 0.1765956, y: -6.279687, z: 59.589127),
                rotation: .init(x: 0.0, y: 3.8018687, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z6t3",
                position: .init(x: 2.8297856, y: -4.799058, z: 57.688732),
                rotation: .init(x: 0.0, y: 0.6336302, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}