//
//  Selbina.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct Selbina: ZoneSceneMetadata {
        public let id = Zone.selbina.rawValue
        public let name = "Selbina"
        public let lines: [ZoneLine] = [
            .init(
                name: "z3v0z3y9",
                position: .init(x: -540.0029, y: 156.71005, z: -209.99525),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 8.0, z: 12.0)
            ),
            .init(
                name: "z3v1",
                position: .init(x: -536.363, y: 157.71297, z: -210.81929),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z3v2z3yb",
                position: .init(x: 439.9431, y: -43.221634, z: 69.98818),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 8.0, z: 12.0)
            ),
            .init(
                name: "z3v3",
                position: .init(x: 444.26953, y: -42.210007, z: 68.51307),
                rotation: .init(x: 0.0, y: 0.46006387, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}