//
//  ShipBoundForMhaura2.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct ShipBoundForMhaura2: ZoneSceneMetadata {
        public let id = Zone.shipBoundForMhaura2.rawValue
        public let name = "Ship bound for Mhaura 2"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}