//
//  ShipBoundForMhaura.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct ShipBoundForMhaura: ZoneSceneMetadata {
        public let id = Zone.shipBoundForMhaura.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z2j0z2i7",
                position: .init(x: -108.94002, y: -7.55756, z: -918.1006),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 40.0)
            ),
            .init(
                name: "z2j1",
                position: .init(x: -102.20988, y: -3.0165997, z: -917.6427),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 10.0)
            ),
            .init(
                name: "z2j4z2q3",
                position: .init(x: 367.70734, y: 16.39857, z: 478.22733),
                rotation: .init(x: 0.0, y: 5.67232, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 70.0)
            ),
            .init(
                name: "z2j5",
                position: .init(x: 363.42972, y: 20.515068, z: 473.82635),
                rotation: .init(x: 0.0, y: 2.530727, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 20.0)
            ),
            .init(
                name: "z2j2z2c3",
                position: .init(x: -36.615032, y: 17.0166, z: 616.61237),
                rotation: .init(x: 0.0, y: 1.0471976, z: 0.0),
                scale: .init(x: 3.0, y: 20.0, z: 50.0)
            ),
            .init(
                name: "z2j3",
                position: .init(x: -31.980944, y: 19.609179, z: 611.32715),
                rotation: .init(x: 0.0, y: 1.0471976, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 15.0)
            ),
            .init(
                name: "z2j6z4r1",
                position: .init(x: -381.9952, y: -32.112896, z: -791.7403),
                rotation: .init(x: 0.0, y: 1.723501, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2j7",
                position: .init(x: -376.17914, y: -30.387312, z: -776.1594),
                rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z2j8z4r3",
                position: .init(x: -792.2288, y: -40.476254, z: -502.04333),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2j9",
                position: .init(x: -774.91986, y: -38.356354, z: -494.9118),
                rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z2jaz2b7",
                position: .init(x: -419.5674, y: -0.21312092, z: 341.17822),
                rotation: .init(x: 0.0, y: 1.0471976, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z2jb",
                position: .init(x: -417.17545, y: 1.5120696, z: 337.20435),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}