//
//  ShipBoundForSelbina.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct ShipBoundForSelbina: ZoneSceneMetadata {
        public let id = Zone.shipBoundForSelbina.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "zmsb",
                position: .init(x: -56.0, y: -2.25, z: -128.5),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 10.0)
            ),
            .init(
                name: "zmsazmsb",
                position: .init(x: -56.0, y: -4.5, z: -140.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 17.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z753",
                position: .init(x: -150.0, y: -3.1, z: -20.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 6.0, z: 25.0)
            ),
            .init(
                name: "z752z745",
                position: .init(x: -165.0, y: -3.5, z: -20.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 4.0, y: 8.0, z: 42.0)
            ),
            .init(
                name: "z755",
                position: .init(x: -126.0, y: 6.6321945, z: 28.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 2.0)
            ),
            .init(
                name: "z754z767",
                position: .init(x: -122.0, y: 4.8739824, z: 28.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 7.0, z: 5.0)
            ),
            .init(
                name: "z757",
                position: .init(x: 65.0, y: -41.6, z: -16.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 2.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}