//
//  ShipBoundForSelbina.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct ShipBoundForSelbina: ZoneSceneMetadata {
    public let id = Zone.shipBoundForSelbina.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z2t1",
            position: .init(x: -16.4717, y: -54.180294, z: 140.003),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z2t0z2s5",
            position: .init(x: -30.049547, y: -58.027317, z: 140.03355),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 8.0, y: 20.0, z: 20.0)
        ),
        .init(
            name: "z2t3",
            position: .init(x: 86.1312, y: -65.8175, z: 273.861),
            rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
            scale: .init(x: 2.0, y: 7.0, z: 12.0)
        ),
        .init(
            name: "z2t2z6e1",
            position: .init(x: 79.18075, y: -70.08913, z: 280.84103),
            rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
            scale: .init(x: 8.0, y: 20.0, z: 20.0)
        ),
        .init(
            name: "z2t4z2s7",
            position: .init(x: 56.1403, y: -37.462086, z: -199.961),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 8.0, y: 40.0, z: 50.0)
        ),
        .init(
            name: "z2t5",
            position: .init(x: 81.5817, y: -29.24236, z: -199.921),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 3.0, y: 15.0, z: 15.0)
        ),
        .init(
            name: "z2t6z5a1",
            position: .init(x: 199.98198, y: -8.5, z: -544.5742),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 8.0, y: 20.0, z: 30.0)
        ),
        .init(
            name: "z2t7",
            position: .init(x: 200.015, y: -3.187317, z: -536.074),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 6.0, z: 6.0)
        ),
        .init(
            name: "z2t9",
            position: .init(x: 660.078, y: -21.882986, z: -588.047),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 2.0, y: 4.0, z: 6.0)
        ),
        .init(
            name: "z2t8z5a3",
            position: .init(x: 661.624, y: -21.97446, z: -595.631),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 5.0, y: 10.0, z: 20.0)
        ),
        .init(
            name: "z2tb",
            position: .init(x: 818.507, y: -66.7738, z: 659.68),
            rotation: .init(x: 0.0, y: 2.1816616, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z2taz4m1",
            position: .init(x: 821.6808, y: -68.00337, z: 666.4428),
            rotation: .init(x: 0.0, y: 2.0071287, z: 0.0),
            scale: .init(x: 5.0, y: 10.0, z: 20.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}