//
//  SihGates.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct SihGates: ZoneSceneMetadata {
        public let id = Zone.sihGates.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z6z0z3e3",
                position: .init(x: 0.0038390383, y: -3.52557, z: -180.05661),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z6z1",
                position: .init(x: -0.010868903, y: -1.8481517, z: -176.13252),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z6z2zlm9",
                position: .init(x: 0.000143833, y: -3.3164196, z: 365.058),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z6z3",
                position: .init(x: 0.0045516044, y: -1.6402766, z: 362.018),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}