//
//  SilverSeaRouteToNashmau.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct SilverSeaRouteToNashmau: ZoneSceneMetadata {
        public let id = Zone.silverSeaRouteToNashmau.rawValue
        public let name = "Silver Sea route to Nashmau"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}