//
//  SilverSeaRouteToNashmau.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct SilverSeaRouteToNashmau: ZoneSceneMetadata {
    public let id = Zone.silverSeaRouteToNashmau.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z3k0z355",
            position: .init(x: -239.07657, y: -3.0981216, z: -19.953308),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 7.0, z: 14.0)
        ),
        .init(
            name: "z3k1",
            position: .init(x: -231.231, y: -2.6720004, z: -19.1541),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z3k2z353",
            position: .init(x: 39.950764, y: -3.1021385, z: -140.068),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 7.0, z: 14.0)
        ),
        .init(
            name: "z3k3",
            position: .init(x: 45.24951, y: -2.115076, z: -140.56223),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}