//
//  SilverSeaRemnants.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct SilverSeaRemnants: ZoneSceneMetadata {
    public let id = Zone.silverSeaRemnants.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z5p0z3gb",
            position: .init(x: 299.99402, y: 12.060863, z: -85.013374),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 9.0, z: 12.0)
        ),
        .init(
            name: "z5p1",
            position: .init(x: 299.9383, y: 14.160391, z: -81.801605),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z5p2z3g9",
            position: .init(x: 100.34029, y: -3.6522996, z: -323.96124),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 9.0, z: 12.0)
        ),
        .init(
            name: "z5p3",
            position: .init(x: 100.28456, y: -1.7684734, z: -320.74948),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z5p4z5r1",
            position: .init(x: -58.748272, y: 46.83321, z: 110.260704),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 9.0, z: 13.0)
        ),
        .init(
            name: "z5p5",
            position: .init(x: -60.296482, y: 48.88444, z: 105.96663),
            rotation: .init(x: 0.0, y: 1.8349066, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z5p6z3fd",
            position: .init(x: -419.27097, y: 27.025452, z: 227.96799),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 9.0, z: 13.0)
        ),
        .init(
            name: "z5p7",
            position: .init(x: -418.66364, y: 28.915976, z: 231.7008),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}