//
//  SilverSeaRemnants.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct SilverSeaRemnants: ZoneSceneMetadata {
        public let id = Zone.silverSeaRemnants.rawValue
        public let name = "Silver Sea Remnants"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}