//
//  SouthernSanDOriaS.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct SouthernSanDOriaS: ZoneSceneMetadata {
        public let id = Zone.southernSanDOriaS.rawValue
        public let name = "Southern San d'Oria [S]"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}