//
//  SouthGustaberg.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct SouthGustaberg: ZoneSceneMetadata {
        public let id = Zone.southGustaberg.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z3w0z2s9",
                position: .init(x: 99.7234, y: -2.1658027, z: -45.6687),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 15.0, y: 8.0, z: 3.0)
            ),
            .init(
                name: "z3w1",
                position: .init(x: 100.002, y: -2.0618014, z: -38.021),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.5)
            ),
            .init(
                name: "z3w2z3y7",
                position: .init(x: -7.914858, y: -2.3912, z: -60.876644),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 15.0, y: 8.0, z: 3.0)
            ),
            .init(
                name: "z3w3",
                position: .init(x: -2.0485444, y: -2.2019129, z: -60.185368),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.5)
            ),
            .init(
                name: "z3w5",
                position: .init(x: 125.8519, y: -22.0966, z: 180.40273),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z3w4z3x1",
                position: .init(x: 130.04572, y: -22.8125, z: 181.5723),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 15.0, y: 8.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}