//
//  SpireOfMea.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct SpireOfMea: ZoneSceneMetadata {
    public let id = Zone.spireOfMea.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z3i0z6u5",
            position: .init(x: 140.00412, y: 5.979361, z: -480.00366),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z3i1",
            position: .init(x: 139.99675, y: 8.90343, z: -476.95602),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z3i2z3j1",
            position: .init(x: -642.01526, y: 13.91822, z: 459.99332),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z3i3",
            position: .init(x: -638.71436, y: 16.86531, z: 459.966),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z3i4z541",
            position: .init(x: -289.882, y: -26.699377, z: 320.036),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 2.0, y: 14.0, z: 20.0)
        ),
        .init(
            name: "z3i5",
            position: .init(x: -286.27124, y: -21.618652, z: 320.0839),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}