//
//  StellarFulcrum.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct StellarFulcrum: ZoneSceneMetadata {
        public let id = Zone.stellarFulcrum.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z291",
                position: .init(x: 86.1312, y: -65.8175, z: 273.861),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 2.0, y: 7.0, z: 12.0)
            ),
            .init(
                name: "z290z281",
                position: .init(x: 79.18075, y: -70.08913, z: 280.84103),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 8.0, y: 20.0, z: 20.0)
            ),
            .init(
                name: "z293",
                position: .init(x: 693.0682, y: -21.256094, z: -590.71265),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 4.0, z: 6.0)
            ),
            .init(
                name: "z292z2a1",
                position: .init(x: 706.18726, y: -21.9745, z: -591.22565),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 5.0, y: 10.0, z: 20.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}