//
//  StellarFulcrum.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct StellarFulcrum: ZoneSceneMetadata {
        public let id = Zone.stellarFulcrum.rawValue
        public let name = "Stellar Fulcrum"
        public let lines: [ZoneLine] = [
            .init(
                name: "z5k0z3c7",
                position: .init(x: -380.01526, y: -15.505676, z: 400.99585),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z5k1",
                position: .init(x: -380.0347, y: -13.547713, z: 398.03162),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z5k2z3c9",
                position: .init(x: 19.99953, y: -21.59568, z: 440.97867),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z5k3",
                position: .init(x: 19.990683, y: -19.56612, z: 438.0082),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}