//
//  TheAshuTalif.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct TheAshuTalif: ZoneSceneMetadata {
        public let id = Zone.theAshuTalif.rawValue
        public let name = "The Ashu Talif"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}