//
//  TheCelestialNexus.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct TheCelestialNexus: ZoneSceneMetadata {
    public let id = Zone.theCelestialNexus.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z700z4w3",
            position: .init(x: -19.216085, y: -3.6089008, z: -67.52518),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z701",
            position: .init(x: -19.23754, y: -2.1625242, z: -63.96412),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}