//
//  TheGardenOfRuHmet.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct TheGardenOfRuHmet: ZoneSceneMetadata {
        public let id = Zone.theGardenOfRuHmet.rawValue
        public let name = "The Garden of Ru'Hmet"
        public let lines: [ZoneLine] = [
            .init(
                name: "z1w0z1f1",
                position: .init(x: 359.96085, y: -1.7704469, z: -179.99771),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 12.0, z: 12.0)
            ),
            .init(
                name: "z1w1",
                position: .init(x: 356.5028, y: -0.3643534, z: -179.60724),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.5)
            ),
            .init(
                name: "z1w2z1f3",
                position: .init(x: 20.015686, y: 4.5660825, z: -120.01697),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 14.0)
            ),
            .init(
                name: "z1w3",
                position: .init(x: 20.007221, y: 6.33235, z: -116.514534),
                rotation: .init(x: 0.0, y: 4.537856, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.5)
            ),
            .init(
                name: "z1w4z1f5",
                position: .init(x: -48.856724, y: 27.092285, z: -223.65643),
                rotation: .init(x: 0.0, y: 5.7595863, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1w5",
                position: .init(x: -51.7758, y: 28.509937, z: -225.53067),
                rotation: .init(x: 0.0, y: 2.5307274, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.5)
            ),
            .init(
                name: "z1w6z1f7",
                position: .init(x: -194.08095, y: -20.833546, z: -420.93176),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1w7",
                position: .init(x: -196.82442, y: -19.14491, z: -420.5653),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.0)
            ),
            .init(
                name: "z1w8z1f9",
                position: .init(x: 101.07547, y: 6.389968, z: 154.99072),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1w9",
                position: .init(x: 101.428, y: 8.673251, z: 151.549),
                rotation: .init(x: 0.0, y: 1.7802358, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.5)
            ),
            .init(
                name: "z1waz1fb",
                position: .init(x: -140.00099, y: 3.0021038, z: 122.00275),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1wb",
                position: .init(x: -140.00214, y: 6.012104, z: 118.50282),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.5)
            ),
            .init(
                name: "z1wcz1fd",
                position: .init(x: -405.0597, y: 0.34525242, z: -140.03912),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1wd",
                position: .init(x: -408.47516, y: 3.34181, z: -139.98311),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.0)
            ),
            .init(
                name: "z1wez1ff",
                position: .init(x: -219.92804, y: 0.39770722, z: -153.0119),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1wf",
                position: .init(x: -220.78593, y: 3.7633514, z: -149.67432),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.0)
            ),
            .init(
                name: "z1wgz1fh",
                position: .init(x: -200.8197, y: -22.14182, z: -260.0502),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1wh",
                position: .init(x: -204.8257, y: -17.7969, z: -259.89343),
                rotation: .init(x: 0.0, y: 3.403392, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.0)
            ),
            .init(
                name: "z1wiz1fj",
                position: .init(x: -359.0012, y: -25.301266, z: -259.97025),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1wj",
                position: .init(x: -354.967, y: -20.749746, z: -260.01),
                rotation: .init(x: 0.0, y: 6.0562925, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.0)
            ),
            .init(
                name: "z1wkz1g3",
                position: .init(x: 519.9354, y: -38.039703, z: 459.90204),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1wl",
                position: .init(x: 516.5979, y: -34.888443, z: 459.89008),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.0)
            ),
            .init(
                name: "z1wmz1g5",
                position: .init(x: 242.45013, y: -37.642403, z: 500.04953),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1wn",
                position: .init(x: 245.50159, y: -34.853245, z: 499.93466),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.0)
            ),
            .init(
                name: "z1woz1q3",
                position: .init(x: -539.9987, y: 11.703003, z: -160.09119),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 15.0, z: 15.0)
            ),
            .init(
                name: "z1wp",
                position: .init(x: -539.5665, y: 14.995827, z: -163.88683),
                rotation: .init(x: 0.0, y: 1.8325957, z: 0.0),
                scale: .init(x: 1.0, y: 4.5, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}