//
//  TheSanctuaryOfZiTah.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct TheSanctuaryOfZiTah: ZoneSceneMetadata {
        public let id = Zone.theSanctuaryOfZiTah.rawValue
        public let name = "The Sanctuary of Zi'Tah"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}