//
//  ThroneRoomS.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct ThroneRoomS: ZoneSceneMetadata {
    public let id = Zone.throneRoomS.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z540z3i5",
            position: .init(x: 459.99304, y: -4.8804817, z: -106.484),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 12.0, z: 10.0)
        ),
        .init(
            name: "z541",
            position: .init(x: 460.02246, y: -1.7699268, z: -103.441864),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}