//
//  ToraimaraiCanal.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct ToraimaraiCanal: ZoneSceneMetadata {
        public let id = Zone.toraimaraiCanal.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z3a0z397",
                position: .init(x: -625.8019, y: -50.081394, z: 159.84825),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 24.0)
            ),
            .init(
                name: "z3a1",
                position: .init(x: -620.614, y: -46.4696, z: 159.343),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3a2z6x1",
                position: .init(x: 187.7973, y: -6.094526, z: -227.49916),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 24.0)
            ),
            .init(
                name: "z3a3",
                position: .init(x: 186.72298, y: -3.4825022, z: -223.50995),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z3a4z5i3",
                position: .init(x: -360.092, y: -45.41005, z: 315.477),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 15.0)
            ),
            .init(
                name: "z3a5",
                position: .init(x: -356.2191, y: -43.10721, z: 314.8728),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z3a6z5x1",
                position: .init(x: 444.1349, y: 15.322005, z: 201.02193),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z3a7",
                position: .init(x: 443.994, y: 16.4638, z: 198.161),
                rotation: .init(x: 0.0, y: 1.3962634, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z3a8z041",
                position: .init(x: -279.98666, y: 14.891075, z: -324.01932),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z3a9",
                position: .init(x: -276.52917, y: 16.4033, z: -324.5189),
                rotation: .init(x: 0.0, y: 0.2617994, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}