//
//  UpperJeuno.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct UpperJeuno: ZoneSceneMetadata {
        public let id = Zone.upperJeuno.rawValue
        public let name = "Upper Jeuno"
        public let lines: [ZoneLine] = [
            .init(
                name: "z3y2z3x5",
                position: .init(x: 291.23032, y: -27.26481, z: 249.33589),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z3y3",
                position: .init(x: 295.374, y: -26.69072, z: 249.657),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z3y1",
                position: .init(x: 276.23508, y: -42.35915, z: 149.94415),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z3y0z3x3",
                position: .init(x: 273.0188, y: -43.5001, z: 150.41644),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z3y5",
                position: .init(x: 55.237038, y: -14.922767, z: 70.061104),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z3y4z3x7",
                position: .init(x: 50.503727, y: -15.8396, z: 70.59488),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z3y6z3w3",
                position: .init(x: -251.34435, y: -3.36524, z: -69.67244),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 10.0)
            ),
            .init(
                name: "z3y7",
                position: .init(x: -255.96066, y: -2.7114594, z: -69.828064),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z3y8z3v1",
                position: .init(x: 443.24, y: -43.0333, z: 169.684),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z3y9",
                position: .init(x: 439.81433, y: -42.480824, z: 169.75522),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z3yaz3v3",
                position: .init(x: 440.90802, y: -43.149208, z: 69.94867),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 3.0, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z3yb",
                position: .init(x: 437.23538, y: -42.062553, z: 68.56439),
                rotation: .init(x: 0.0, y: 2.5878136, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}