//
//  ValkurmDunes.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct ValkurmDunes: ZoneSceneMetadata {
    public let id = Zone.valkurmDunes.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z080z073",
            position: .init(x: -713.01556, y: 18.686747, z: 458.0113),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z081",
            position: .init(x: -709.50793, y: 18.065767, z: 456.24124),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z082z075",
            position: .init(x: 630.96924, y: 15.5391245, z: -696.83136),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z083",
            position: .init(x: 627.53644, y: 15.736637, z: -695.3638),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}