//
//  ValkurmDunes.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct ValkurmDunes: ZoneSceneMetadata {
        public let id = Zone.valkurmDunes.rawValue
        public let name = "Valkurm Dunes"
        public let lines: [ZoneLine] = [
            .init(
                name: "z0q0z0o3",
                position: .init(x: 9.902101, y: -31.5664, z: 157.16246),
                rotation: .init(x: 0.0, y: 5.6723204, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z0q1",
                position: .init(x: 7.4245, y: -31.200506, z: 155.00882),
                rotation: .init(x: 0.0, y: 2.4783676, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z0q2z0o5",
                position: .init(x: 16.107676, y: -27.795998, z: 116.19412),
                rotation: .init(x: 0.0, y: 0.6981317, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z0q3",
                position: .init(x: 13.658952, y: -27.742466, z: 118.25476),
                rotation: .init(x: 0.0, y: 3.9095376, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z0q4z0p3",
                position: .init(x: -48.435024, y: -34.161816, z: 159.97151),
                rotation: .init(x: 0.0, y: 0.6981317, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z0q5",
                position: .init(x: -46.46457, y: -32.598995, z: 158.10513),
                rotation: .init(x: 0.0, y: 0.6981317, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z0q6z0p5",
                position: .init(x: -39.22427, y: -31.3642, z: 117.01633),
                rotation: .init(x: 0.0, y: 5.585054, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z0q7",
                position: .init(x: -37.079, y: -30.027662, z: 118.78269),
                rotation: .init(x: 0.0, y: 5.585054, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z0q8z0w1",
                position: .init(x: -0.03356503, y: -11.217811, z: -41.98681),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z0q9",
                position: .init(x: -0.1725094, y: -9.572134, z: -39.70576),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z0qb",
                position: .init(x: 27.97066, y: -14.068005, z: 43.73544),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 5.0)
            ),
            .init(
                name: "z0qaz0r1",
                position: .init(x: 27.98882, y: -16.337465, z: 57.05322),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 14.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}