//
//  VunkerlInletS.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct VunkerlInletS: ZoneSceneMetadata {
        public let id = Zone.vunkerlInletS.rawValue
        public let name = "Vunkerl Inlet [S]"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}