//
//  WajaomWoodlands.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct WajaomWoodlands: ZoneSceneMetadata {
        public let id = Zone.wajaomWoodlands.rawValue
        public let name = "Wajaom Woodlands"
        public let lines: [ZoneLine] = [
            .init(
                name: "z1h0z271",
                position: .init(x: 42.910114, y: -9.50842, z: -24.006039),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z1h1",
                position: .init(x: 40.657894, y: -7.526653, z: -24.001135),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1h4z275",
                position: .init(x: -42.911346, y: -9.508419, z: 23.997322),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z1h2z273",
                position: .init(x: 16.000446, y: -9.50842, z: 82.89518),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.5, y: 10.0, z: 12.0)
            ),
            .init(
                name: "z1h3",
                position: .init(x: 15.998616, y: -7.534547, z: 80.664474),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z1h5",
                position: .init(x: -40.616745, y: -7.5652733, z: 24.000175),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}