//
//  WalkOfEchoesP2.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct WalkOfEchoesP2: ZoneSceneMetadata {
    public let id = Zone.walkOfEchoesP2.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z4k0z2q5",
            position: .init(x: -300.0, y: -15.5057, z: 160.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z4k1",
            position: .init(x: -300.0, y: -13.5477, z: 157.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z4k2z2q7",
            position: .init(x: 100.0, y: -21.5957, z: 200.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 10.0)
        ),
        .init(
            name: "z4k3",
            position: .init(x: 100.0, y: -19.5661, z: 197.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}