//
//  WalkOfEchoes.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct WalkOfEchoes: ZoneSceneMetadata {
        public let id = Zone.walkOfEchoes.rawValue
        public let name = "Walk of Echoes"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}