//
//  WalkOfEchoes.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct WalkOfEchoes: ZoneSceneMetadata {
        public let id = Zone.walkOfEchoes.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z6v0z3h5",
                position: .init(x: -20.585844, y: 6.411834, z: -128.04628),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z6v1",
                position: .init(x: -20.051926, y: 6.074182, z: -122.407646),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}