//
//  WaughroonShrine.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct WaughroonShrine: ZoneSceneMetadata {
        public let id = Zone.waughroonShrine.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z4t2z361",
                position: .init(x: -499.99973, y: -23.837646, z: 4.0009933),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z4t3",
                position: .init(x: -500.00406, y: -21.82379, z: 0.35830843),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4t4z3h3",
                position: .init(x: -523.01953, y: -33.357418, z: 340.04834),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z4t5",
                position: .init(x: -519.36096, y: -31.872042, z: 340.02008),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z4t0z4s3",
                position: .init(x: 459.97903, y: -42.93559, z: 156.97272),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 14.0)
            ),
            .init(
                name: "z4t1",
                position: .init(x: 459.9674, y: -41.72817, z: 160.62737),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}