//
//  WaughroonShrine.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct WaughroonShrine: ZoneSceneMetadata {
        public let id = Zone.waughroonShrine.rawValue
        public let name = "Waughroon Shrine"
        public let lines: [ZoneLine] = [
            .init(
                name: "z6g0z6f7",
                position: .init(x: -111.802216, y: -11.876427, z: -136.49765),
                rotation: .init(x: 0.0, y: 0.7853982, z: 0.0),
                scale: .init(x: 10.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "z6g1",
                position: .init(x: -107.682, y: -10.301207, z: -132.215),
                rotation: .init(x: 0.0, y: 5.497787, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "zmr4zmr5",
                position: .init(x: 83.260414, y: -19.486214, z: -139.28194),
                rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
                scale: .init(x: 10.0, y: 10.0, z: 2.0)
            ),
            .init(
                name: "zmr5",
                position: .init(x: 79.361755, y: -18.173212, z: -135.45015),
                rotation: .init(x: 0.0, y: 3.926991, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}