//
//  WestSarutabaruta.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct WestSarutabaruta: ZoneSceneMetadata {
        public let id = Zone.westSarutabaruta.rawValue
        public let name = "West Sarutabaruta"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}