//
//  WestRonfaure.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct WestRonfaure: ZoneSceneMetadata {
        public let id = Zone.westRonfaure.rawValue
        public let name = "West Ronfaure"
        public let lines: [ZoneLine] = [
            .init(
                name: "z7k0z7a7",
                position: .init(x: 60.0, y: -15.5, z: 85.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 14.0, y: 11.0, z: 2.0)
            ),
            .init(
                name: "z7k1",
                position: .init(x: 60.0, y: -12.0871, z: 80.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z7k2z7a5",
                position: .init(x: 125.0, y: -15.6, z: 380.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 14.0, y: 11.0, z: 2.0)
            ),
            .init(
                name: "z7k3",
                position: .init(x: 120.0, y: -12.087789, z: 380.0),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z7k6z7i5",
                position: .init(x: 60.0, y: -35.5, z: 525.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 14.0, y: 11.0, z: 2.0)
            ),
            .init(
                name: "z7k7",
                position: .init(x: 60.0, y: -32.1, z: 520.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
            .init(
                name: "z7k4z7e1",
                position: .init(x: -325.0, y: -45.830612, z: 340.0),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 14.0, y: 11.0, z: 2.0)
            ),
            .init(
                name: "z7k5",
                position: .init(x: -320.5, y: -42.1, z: 340.0),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 4.0, z: 4.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}