//
//  WesternAdoulin.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/22/22
//
public extension Zone {
    struct WesternAdoulin: ZoneSceneMetadata {
        public let id = Zone.westernAdoulin.rawValue
        public let lines: [ZoneLine] = [
            .init(
                name: "z340z333",
                position: .init(x: 600.017, y: -6.5172567, z: -260.094),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 20.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z341",
                position: .init(x: 596.6257, y: -2.4954767, z: -259.97943),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z342z4h1",
                position: .init(x: -437.02124, y: -52.94133, z: 20.018042),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 20.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z343",
                position: .init(x: -433.2485, y: -48.742424, z: 20.009903),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
            .init(
                name: "z344z051",
                position: .init(x: -131.77931, y: -24.316113, z: 139.01736),
                rotation: .init(x: 0.0, y: 1.2217305, z: 0.0),
                scale: .init(x: 20.0, y: 15.0, z: 2.0)
            ),
            .init(
                name: "z345",
                position: .init(x: -136.28651, y: -23.268015, z: 137.30247),
                rotation: .init(x: 0.0, y: 2.268928, z: 0.0),
                scale: .init(x: 1.0, y: 5.0, z: 5.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}