//
//  WestRonfaure.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct WestRonfaure: ZoneSceneMetadata {
    public let id = Zone.westRonfaure.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z4a2z3d7",
            position: .init(x: 121.47959, y: -13.449585, z: 139.98712),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z4a3",
            position: .init(x: 118.37758, y: -11.9345875, z: 140.06844),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z4a0z495",
            position: .init(x: -60.005695, y: -4.747921, z: -42.501022),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 8.0, z: 12.0)
        ),
        .init(
            name: "z4a1",
            position: .init(x: -60.00645, y: -2.9151378, z: -39.500923),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}