//
//  WindurstWoods.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct WindurstWoods: ZoneSceneMetadata {
    public let id = Zone.windurstWoods.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z2o0z2n3",
            position: .init(x: -576.17816, y: -11.372, z: -733.59344),
            rotation: .init(x: 0.0, y: 5.759587, z: 0.0),
            scale: .init(x: 3.0, y: 15.0, z: 20.0)
        ),
        .init(
            name: "z2o1",
            position: .init(x: -572.10345, y: -7.774469, z: -731.52954),
            rotation: .init(x: 0.0, y: 5.759587, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z2o2z2p1",
            position: .init(x: 820.0, y: 23.5922, z: 121.0),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 10.0)
        ),
        .init(
            name: "z2o3",
            position: .init(x: 820.0, y: 25.782135, z: 117.990875),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z2o4z2p3",
            position: .init(x: 101.98065, y: -28.6194, z: 375.32263),
            rotation: .init(x: 0.0, y: 0.17453292, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z2o5",
            position: .init(x: 97.01712, y: -27.935938, z: 375.67416),
            rotation: .init(x: 0.0, y: 3.9269907, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z2o6z2p5",
            position: .init(x: 141.72205, y: -24.604015, z: 574.81726),
            rotation: .init(x: 0.0, y: 0.17453292, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z2o7",
            position: .init(x: 137.11157, y: -23.945312, z: 575.6587),
            rotation: .init(x: 0.0, y: 3.9269907, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
        .init(
            name: "z2o8z2p7",
            position: .init(x: 105.38397, y: -17.447746, z: 781.75616),
            rotation: .init(x: 0.0, y: 1.7453293, z: 0.0),
            scale: .init(x: 2.0, y: 10.0, z: 12.0)
        ),
        .init(
            name: "z2o9",
            position: .init(x: 103.991295, y: -15.999284, z: 777.2007),
            rotation: .init(x: 0.0, y: 2.3561945, z: 0.0),
            scale: .init(x: 1.0, y: 4.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}