//
//  WindurstJeunoAirship.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct WindurstJeunoAirship: ZoneSceneMetadata {
    public let id = Zone.windurstJeunoAirship.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z310z303",
            position: .init(x: -543.86993, y: 20.718636, z: -651.96606),
            rotation: .init(x: 0.0, y: 0.0, z: 0.0),
            scale: .init(x: 20.0, y: 10.0, z: 3.0)
        ),
        .init(
            name: "z311",
            position: .init(x: -543.423, y: 22.196754, z: -647.55),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 5.0, z: 6.0)
        ),
        .init(
            name: "z312z321",
            position: .init(x: 551.2572, y: 20.718636, z: 697.03516),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 20.0, y: 10.0, z: 3.0)
        ),
        .init(
            name: "z313",
            position: .init(x: 547.841, y: 23.192379, z: 696.323),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
        .init(
            name: "z314z431",
            position: .init(x: 582.4924, y: 21.080166, z: -377.87134),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 20.0, y: 10.0, z: 3.0)
        ),
        .init(
            name: "z315",
            position: .init(x: 578.7864, y: 23.415524, z: -376.73074),
            rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 4.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}