//
//  WindurstWaters.swift
//
//  Auto-generated by `zone-metadata-generator` on 6/21/22
//
public struct WindurstWaters: ZoneSceneMetadata {
    public let id = Zone.windurstWaters.rawValue
    public let lines: [ZoneLine] = [
        .init(
            name: "z504zlm3",
            position: .init(x: -605.0741, y: -26.5763, z: 433.14767),
            rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
            scale: .init(x: 2.0, y: 7.0, z: 9.0)
        ),
        .init(
            name: "z505",
            position: .init(x: -605.0701, y: -25.48663, z: 436.1359),
            rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z500z3mz",
            position: .init(x: 525.982, y: -42.267773, z: 561.9042),
            rotation: .init(x: 0.0, y: 4.076136, z: 0.0),
            scale: .init(x: 2.0, y: 7.0, z: 9.0)
        ),
        .init(
            name: "z501",
            position: .init(x: 527.7205, y: -41.082344, z: 559.469),
            rotation: .init(x: 0.0, y: 0.93453825, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z502zlm1",
            position: .init(x: 186.96593, y: -177.5203, z: 345.6001),
            rotation: .init(x: 0.0, y: 2.8199143, z: 0.0),
            scale: .init(x: 2.0, y: 7.0, z: 9.0)
        ),
        .init(
            name: "z503",
            position: .init(x: 189.84904, y: -176.45456, z: 346.5314),
            rotation: .init(x: 0.0, y: 5.9615054, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z506zlm5",
            position: .init(x: 62.90534, y: -228.24062, z: 472.5071),
            rotation: .init(x: 0.0, y: 0.31231603, z: 0.0),
            scale: .init(x: 2.0, y: 7.0, z: 9.0)
        ),
        .init(
            name: "z507",
            position: .init(x: 60.079563, y: -227.12495, z: 473.42545),
            rotation: .init(x: 0.0, y: 3.4539135, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
        .init(
            name: "z508zlm7",
            position: .init(x: -234.93405, y: -141.19896, z: 415.98352),
            rotation: .init(x: 0.0, y: 5.3392863, z: 0.0),
            scale: .init(x: 2.0, y: 7.0, z: 9.0)
        ),
        .init(
            name: "z509",
            position: .init(x: -236.69182, y: -140.10928, z: 413.54626),
            rotation: .init(x: 0.0, y: 2.1976962, z: 0.0),
            scale: .init(x: 1.0, y: 3.0, z: 3.0)
        ),
    ]
    public var fog: Fog?
    public var environment: ZoneEnvironment? {
        return .init(
            skybox: nil,
            atmosphere: nil
        )
    }
}