//
//  WindurstWaters.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct WindurstWaters: ZoneSceneMetadata {
        public let id = Zone.windurstWaters.rawValue
        public let name = "Windurst Waters"
        public let lines: [ZoneLine] = [
            .init(
                name: "z440z433",
                position: .init(x: 340.76285, y: 36.668793, z: 20.084679),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z441",
                position: .init(x: 337.90134, y: 38.090893, z: 20.08724),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z442z435",
                position: .init(x: 260.01816, y: 36.67245, z: 40.049076),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z443",
                position: .init(x: 259.9881, y: 38.363247, z: 42.943493),
                rotation: .init(x: 0.0, y: 4.712389, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z444z437",
                position: .init(x: -0.012095958, y: 20.602062, z: 60.008934),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z445",
                position: .init(x: 2.8868995, y: 22.372114, z: 59.957172),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}