//
//  WindurstJeunoAirship.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct WindurstJeunoAirship: ZoneSceneMetadata {
        public let id = Zone.windurstJeunoAirship.rawValue
        public let name = "Windurst-Jeuno Airship"
        public let lines: [ZoneLine] = [
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}