//
//  WindurstWalls.swift
//
//  Auto-generated by `zone-metadata-generator` on 9/22/22
//
public extension Zone {
    struct WindurstWalls: ZoneSceneMetadata {
        public let id = Zone.windurstWalls.rawValue
        public let name = "Windurst Walls"
        public let lines: [ZoneLine] = [
            .init(
                name: "z430z315",
                position: .init(x: -300.0879, y: -1.0846355, z: 96.04378),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 15.0)
            ),
            .init(
                name: "z431",
                position: .init(x: -297.10928, y: 0.008156989, z: 96.00218),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 4.0)
            ),
            .init(
                name: "z432z441",
                position: .init(x: 384.50085, y: 36.716957, z: 19.617315),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z433",
                position: .init(x: 387.38162, y: 38.029144, z: 19.693724),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z434z443",
                position: .init(x: 260.00183, y: 29.128937, z: 1.7301532),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z435",
                position: .init(x: 259.98776, y: 30.446594, z: -0.8106457),
                rotation: .init(x: 0.0, y: 1.5707964, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
            .init(
                name: "z436z445",
                position: .init(x: -31.97535, y: 20.859282, z: 59.82926),
                rotation: .init(x: 0.0, y: 0.0, z: 0.0),
                scale: .init(x: 2.0, y: 8.0, z: 10.0)
            ),
            .init(
                name: "z437",
                position: .init(x: -34.84397, y: 22.35654, z: 59.77486),
                rotation: .init(x: 0.0, y: 3.1415927, z: 0.0),
                scale: .init(x: 1.0, y: 3.0, z: 3.0)
            ),
        ]
        public var fog: Fog?
        public var environment: ZoneEnvironment? {
            return .init(
                skybox: nil,
                atmosphere: nil
            )
        }
    }
}